### ISSUE TITLE
Publishing an asset after processForAllLocales() fails with versionMismatch 

### ISSUE THREAD

**Issue by soliveira-nascent** [contentful/contentful-management.js#101]
We're having the same issue where we're getting a versionMismatch when trying to publish an asset after calling processForAllLocales. We are processing an asset for two locales (en-US, fr-CA). 

See example below:

```javascript
space.createAsset({ fields: rawAsset })
      .then((asset) => asset.processForAllLocales())
      .then((asset) => asset.publish())
      .then((asset) => ({ space, asset }))
      .catch((error) => Promise.reject(error))
```

The issue is intermittent. On occasion this succeeds and at other times it fails. After looking at the processForAllLocales method, it appears to be returning the first object in the array of processed asset objects. My guess would be that the first object may contain an outdated version and therefore causing the versionMismatch when trying to publish.

The code I'm referring to is in `lib/entities/asset.js` line 198

```javascript
return Promise.all(locales.map((locale) => processForLocale.call(self, locale, options)))
.then((assets) => assets[0])
```

As a workaround we've added a `space.getAsset(asset.sys.id)` call before calling `asset.publish()`, but ideally we shouldn't have to make this call

**Comment by Khaledgarbaya** [comment]
Hi @soliveira-nascent ,
Good catch I'll investigate this further and push a fix very soon.
Best,
Khaled

**Comment by arun057** [comment]
Any updates on this? We keep having these intermittent issues as well.

```
const processPublishAsset = (space, asset, resolve) => {
  const assetFile = space.processAssetFile(asset, 'en-US');
  const processedAsset = assetFile.then(asset => getProcessingAsset(space, asset, resolve))
  .catch(logError('asset error'));
};

const getProcessingAsset = (space, asset, resolve) => {
  const assetFile = space.getAsset(asset);
  assetFile.then(serverAsset => {
    if (!serverAsset.fields.file['en-US'].url) {
      setTimeout(() => getProcessingAsset(space, asset, resolve), 300);
    } else {
      space.publishAsset(serverAsset);
      resolve(serverAsset);
    }
  });
};
```

We even wait for the asset url to show up before trying to publish it

**Comment by Khaledgarbaya** [comment]
Hi @arun057,
I don't recall there is a method `processAssetFile` in the space object. Which version of the SDK are you using?
Here is a complete example
```
const contentful = require('contentful-management')

const client = contentful.createClient({
  accessToken: '<content_management_api_key>'
})
client.getSpace('<space_id>')
.then((space) => space.createAssetWithId('<asset_id>', {
  title: {
    'en-US': 'Playsam Streamliner',
    'de-DE': 'Playsam Streamliner'
  },
  file: {
    'en-US': {
      contentType: 'image/jpeg',
      fileName: 'example.jpeg',
      upload: 'https://example.com/example.jpg'
    },
    'de-DE': {
      contentType: 'image/jpeg',
      fileName: 'example.jpeg',
      upload: 'https://example.com/example-de.jpg'
    }
  }
}))
.then((asset) => asset.processForAllLocales())
.then((asset) => console.log(asset))
.catch(console.error)
```

**Comment by ChrisSki** [comment]
Is there a reason this isn't documented @Khaledgarbaya? everything in the Contentful docs reads like you have above, but that doesn't seem to actually publish.
