### ISSUE TITLE
error in documentation for entry.unpublish()

### ISSUE THREAD

**Issue by klokie** [contentful/contentful-management.js#1014]
Hi, I was trying to use the `entry.unpublish()` method, following the [documentation](https://contentful.github.io/contentful-management.js/contentful-management/3.10.0/Entry.html#.unpublish). However, it seems the example is incorrect.
Here's what it says:
```
client.getSpace('<space_id>')
.then((space) => space.getEntry('<entry_id>'))
.then((entry) => entry.unpublish())
.then((entry) => console.log(`Entry ${entry.sys.id} unpublished.`))
.catch(console.error)
```

Here's what it should be, or at least what I had to do to make it work:
```
client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment>'))
.then((environment) => environment.getEntry('<entry_id>'))
.then((entry) => entry.unpublish())
.then((entry) => console.log(`Entry ${entry.sys.id} unpublished.`))
.catch(console.error)
```

**Comment by Spring3** [comment]
Thanks for letting us know, @klokie . We'll prepare the update for the documentation soon

**Comment by Spring3** [comment]
It looks like you referenced a very old version of the sdk. Please refer to the documentation of a more recent version of the sdk for correct examples

Recent as of writing:
https://contentful.github.io/contentful-management.js/contentful-management/7.45.5/interfaces/Entry.html#unpublish
