### ISSUE TITLE
Can't create content type with `Text (Short)`

### ISSUE THREAD

**Issue by chapati23** [contentful/contentful-management.js#114]
How can I create a contentType with type `Text (Short)`.

The default for `type: Text` seems to be `Text (Long)`

**Comment by Khaledgarbaya** [comment]
Hi @chapati23,
For short text you need to use `Symbol`

**Comment by Khaledgarbaya** [comment]
Here is a list of Field types https://contentful.github.io/contentful-management.js/contentful-management/3.7.6/EntryFields.html

**Comment by chapati23** [comment]
worked like a charm, thx
