### ISSUE TITLE
Error in FieldAware

### ISSUE THREAD

**Issue by skazzaks** [contentful/contentful-management.js#117]
I have been successfully using contentful-management for a while now, and it has worked like a charm. Recently, I tried to use an import script that I wrote and my script bombs in field_aware.rb with the following error:
`/home/devon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contentful-management-1.6.0/lib/contentful/management/resource/field_aware.rb:25:in 'block (2 levels) in create_getter': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /home/devon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contentful-management-1.6.0/lib/contentful/management/entry.rb:94:in 'save'
        from import_language_to_contentful.rb:78:in 'block in <main>'
        from /home/devon/.rbenv/versions/2.3.0/lib/ruby/2.3.0/csv.rb:1748:in 'each'
        from /home/devon/.rbenv/versions/2.3.0/lib/ruby/2.3.0/csv.rb:1131:in 'block in foreach'
        from /home/devon/.rbenv/versions/2.3.0/lib/ruby/2.3.0/csv.rb:1282:in 'open'
        from /home/devon/.rbenv/versions/2.3.0/lib/ruby/2.3.0/csv.rb:1130:in 'foreach'
        from import_language_to_contentful.rb:42:in '<main>'
`

I've narrowed it down to only one new contentful content type (all the others work as they used to), but I can't figure out why the new one shouldn't work.  In fact, if I just do:
`require 'contentful/management'
require "csv"
client = Contentful::Management::Client.new('my_num')
space = client.spaces.find('another_num')
e_that_exists = space.entries.find('an_existing_id')
e_that_exists.save
`
I get the error.

Any ideas?

**Comment by axe312ger** [comment]
Hey @skazzaks,

looks like you ended up in the wrong repository, you should reopen your issue here: https://github.com/contentful/contentful-management.rb

All the best,
Benedikt

**Comment by skazzaks** [comment]
Oh! Sorry about that and thank you.
