### ISSUE TITLE
Issue while creating entry in space

### ISSUE THREAD

**Issue by jubinpatel1992** [contentful/contentful-management.js#120]
I am able to createclient but i receive bad request when the code reaches client.getSpace. I receive 400 Bad request error.

```js
var client = contentful.createClient({
    accessToken: 'oauth token',
    agent: proxyAgent
  });
  console.log(client);

  // Create asset
  client.getSpace('space id')
  .then((space) => {
      console.log(space);
    space.createAsset('image/jpeg', {
      fields: {
        file: {
          upload: 'example.jpg'
        }
      }
    })
    .then((asset) => { console.log(asset); });
  });
```

Edit by @axe312ger: Added syntax highlighting

**Comment by axe312ger** [comment]
Hey Jubin,

since we updated our Axios dependency, the configuration for proxies changed. Instead of `agent` use `httpAgent` and `httpsAgent`. See [here](https://github.com/contentful/contentful-management.js#httpagent-default-undefined).

Good luck since proxies can be nasty,
Benedikt

**Comment by jubinpatel1992** [comment]
Hi Benedikt,
I also tried using httpAgent and httpsAgent by setting their values using http-proxy-agent and https-proxy-agent for node.js. But, still getting the same error.

**Comment by axe312ger** [comment]
Maybe using the [proxy config option](https://github.com/contentful/contentful-management.js#proxy-default-undefined) instead of the agents might solve your problem? Did you try that?

**Comment by axe312ger** [comment]
Looks like Axios picks environment variables like `HTTP_PROXY` which might overwrite your given http agent. That's how we solved it:

```
const { env } = process
delete env['http_proxy']
delete env['HTTP_PROXY']
delete env['https_proxy']
delete env['HTTPS_PROXY']

const host = 'https://your.proxy.com'
const port = 1234

const agent = new HttpsProxyAgent({ host, port })

var client = contentful.createClient({
  accessToken: 'oauth token',
  httpsAgent: agent
});
```

**Comment by jubinpatel1992** [comment]
Thank for help it worked.
Is it possible to upload file from localhost

**Comment by Khaledgarbaya** [comment]
Sorry I'm late to the party but isn't that already handled [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/gatsby-node.js#L35)
