### ISSUE TITLE
createAssetFromFiles fails in react-native

### ISSUE THREAD

**Issue by jdwillemse** [contentful/contentful-management.js#123]
I'm trying to upload a file to my space but get this error:
```Error: Unable to locate a file to upload.```

This is the function I'm using:
```
const uploadImage = ({ fileName, uri }) => {
  const image = {
    fields: {
      title: {
        'en-GB': fileName
      },
      file: {
        'en-GB': {
          contentType: 'application/jpeg',
          fileName: fileName,
          data: RNFetchBlob.wrap(uri),
        }
      }
    }
  };
  return getWorkspace
    .then((space) => space.createAssetFromFiles(image))
    .then((asset) => asset.processForAllLocales())
    .then((asset) => asset.publish());
};
```

I am able to upload a svg file which leads me to believe the problem is the blob stream. I'm trying to use `react-native-fetch-blob` and according to the docs wrap is meant to work for what I need.

The `uri` I'm using looks something like this (because I'm testing on ios simulator):
`/Users/USERNAME/Library/Developer/CoreSimulator/Devices/B5A4F0A8-197E-47AF-A887-B07302EED70A/data/Containers/Data/Application/47CD754B-896E-4CBA-8977-952B77760AAA/Documents/images/42BA29F4-FDA6-4B46-83DA-A0918CCA6EE8.jpg`

What am I missing here?

**Comment by Khaledgarbaya** [comment]
Hey @jdwillemse you need to use `file` instead of `data` 
```
const image = {
    fields: {
      title: {
        'en-GB': fileName
      },
      file: {
        'en-GB': {
          contentType: 'application/jpeg',
          fileName: fileName,
          file: RNFetchBlob.wrap(uri),
        }
      }
    }
  };
```

**Comment by jdwillemse** [comment]
Sorry that was me trying desperate things to solve the problem. Changing `data` to `file` doesn't solve my problem. I don't get the error anymore and the entry is created, but the entry has a broken image icon instead of the image.

**Comment by Khaledgarbaya** [comment]
Hi @jdwillemse did you add the asset to your entry, can provide the full code ?

**Comment by jdwillemse** [comment]
This is the full module as I'm using it:
```
import RNFetchBlob from 'react-native-fetch-blob';

import { LOCALE } from '../constants';
import { getWorkspace } from './contentful';

const uploadImage = ({ fileName, uri }) => {
  const timestamp = new Date().getTime();
  const image = {
    fields: {
      title: {
        [LOCALE]: `Asset ${timestamp}`
      },
      file: {
        [LOCALE]: {
          contentType: 'application/jpeg',
          fileName: `${fileName}-${timestamp}.jpg`,
          file: RNFetchBlob.wrap(uri),
        }
      }
    }
  };
  return getWorkspace
    .then((space) => space.createAssetFromFiles(image))
    .then((asset) => asset.processForAllLocales())
    .then((asset) => asset.publish());
};

export default uploadImage;
```

and the `./contentful` file is this:
```
import { createClient as createManagementClient } from 'contentful-management';

import {
  CONTENT_MANAGE_API_TOKEN,
  CONTENT_API_SPACE_ID,
} from '../constants';

export const managementClient = createManagementClient({
  accessToken: CONTENT_MANAGE_API_TOKEN
});

export const getWorkspace = managementClient.getSpace(CONTENT_API_SPACE_ID);
```

This is all I do with the API

**Comment by Khaledgarbaya** [comment]
@jdwillemse can you try your code in a normal node environment, I am just trying to see if it is a react native issue or a general issue

**Comment by jdwillemse** [comment]
When I run this code in node using fs.createReadStream the upload is successful

**Comment by Khaledgarbaya** [comment]
did you try to load the file and pass it as a blob of data?

**Comment by jdwillemse** [comment]
Yes, but I don't know if I did it correctly. Where do I find documentation for that?
