### ISSUE TITLE
Processing upload asset seems to fail without notice

### ISSUE THREAD

**Issue by Charl13** [contentful/contentful-management.js#126]
Hello support,

We're using Contentful for the first time on one our Javascript projects. We've had succes up until the point of processing an _Asset_ linked to an _Upload_. The process call returns an _HTTP 204 no content_ response just like described in the CMA documentation but in the Contentful CMS at **Media** the _Asset_ isn't process. Even after waiting for hours.

So we've tried to make this work with cURL to avoid the use of resources that could interfere. But without success. Please see the below cURL commands we've used to upload and create and asset.

```
charlie@XKEYSCORE-WEB-SERVER:/var/www/reactnative$ curl -s -H "Authorization: Bearer <TOKEN"  -H "Content-Type: application/octet-stream" -d @/home/charlie/Pictures/680380420.jpg https://upload.contentful.com/spaces/<SPACE ID>/uploads
{
  "sys": {
    "id": "2Sw7cprHNNKTzEJ2IlE5Le",
    "type": "Upload",
    "createdAt": "2017-07-20T12:41:58.000Z",
    "expiresAt": "2017-07-22T00:00:00.000Z",
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "<SPACE ID>"
      }
    },
    "createdBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "3Q1HvKZp4FmLhq4Vpm8fOe"
      }
    }
  }
}
```

```
charlie@XKEYSCORE-WEB-SERVER:/var/www/reactnative$ curl -s -H "Authorization: Bearer <TOKEN>"  -H "Content-Type: application/vn.contentful.management.v1+json" -d '{ "fields": { "title": { "en-GB": "My cute cat pic" }, "file": { "en-GB": { "contentType": "image/jpeg", "fileName": "680380420.jpg", "uploadFrom": { "sys": { "type": "Link", "linkType": "Upload", "id": "2Sw7cprHNNKTzEJ2IlE5Le" } } } } } }' https://api.contentful.com/spaces/<SPACE ID>/assets
{
  "fields": {
    "title": {
      "en-GB": "My cute cat pic"
    },
    "file": {
      "en-GB": {
        "contentType": "image/jpeg",
        "fileName": "680380420.jpg",
        "uploadFrom": {
          "sys": {
            "type": "Link",
            "linkType": "Upload",
            "id": "2Sw7cprHNNKTzEJ2IlE5Le"
          }
        }
      }
    }
  },
  "sys": {
    "id": "70QFpOwagEmuMECiCEKs22",
    "type": "Asset",
    "createdAt": "2017-07-20T12:42:38.710Z",
    "createdBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "3Q1HvKZp4FmLhq4Vpm8fOe"
      }
    },
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "<SPACE ID>"
      }
    },
    "version": 1,
    "updatedAt": "2017-07-20T12:42:38.717Z",
    "updatedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "3Q1HvKZp4FmLhq4Vpm8fOe"
      }
    }
  }
}
```

```
charlie@XKEYSCORE-WEB-SERVER:/var/www/reactnative$ curl -v -s -X PUT -H "Authorization: Bearer <TOKEN>" -H "X-Contentful-Version: 1" https://api.contentful.com/spaces/<SPACE ID>/assets/70QFpOwagEmuMECiCEKs22/files/en-GB/process
*   Trying 149.126.74.254...
* Connected to api.contentful.com (149.126.74.254) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: incapsula.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=Delaware,L=Dover,O=Incapsula Inc,CN=incapsula.com
* 	 start date: Mon, 03 Jul 2017 01:31:49 GMT
* 	 expire date: Fri, 03 Nov 2017 11:22:23 GMT
* 	 issuer: C=BE,O=GlobalSign nv-sa,CN=GlobalSign CloudSSL CA - SHA256 - G3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> PUT /spaces/<SPACE ID>/assets/70QFpOwagEmuMECiCEKs22/files/en-GB/process HTTP/1.1
> Host: api.contentful.com
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer <TOKEN>
> X-Contentful-Version: 1
> 
< HTTP/1.1 204 No Content
< Access-Control-Allow-Headers: Accept,Accept-Language,Authorization,Cache-Control,Content-Length,Content-Range,Content-Type,DNT,Destination,Expires,If-Match,If-Modified-Since,If-None-Match,Keep-Alive,Last-Modified,Origin,Pragma,Range,User-Agent,X-Http-Method-Override,X-Mx-ReqToken,X-Requested-With,X-Contentful-Version,X-Contentful-Content-Type,X-Contentful-Organization,X-Contentful-Skip-Transformation,X-Contentful-User-Agent
< Access-Control-Allow-Methods: DELETE,GET,HEAD,POST,PUT,OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Etag
< Access-Control-Max-Age: 1728000
< CF-Space-Id: <SPACE ID>
< Content-Type: application/vnd.contentful.management.v1+json
< Date: Thu, 20 Jul 2017 12:43:18 GMT
< Server: Contentful
< Strict-Transport-Security: max-age=15768000
< X-Content-Type-Options: nosniff
< X-Contentful-RateLimit-Hour-Limit: 36000
< X-Contentful-RateLimit-Hour-Remaining: 35826
< X-Contentful-RateLimit-Reset: 0
< X-Contentful-RateLimit-Second-Limit: 10
< X-Contentful-RateLimit-Second-Remaining: 9
< X-Contentful-Request-Id: a6019547898c66651a811acdb55f8c19
< Connection: keep-alive
< Set-Cookie: visid_incap_673446=hNsMJe+vTW6/yKdvy3j1cGWlcFkAAAAAQUIPAAAAAADOpvv1S7MMOyNmyroRp2hN; expires=Fri, 20 Jul 2018 07:55:45 GMT; path=/; Domain=.contentful.com
< Set-Cookie: nlbi_673446=7wMYD5hvzxochzow6lKYhQAAAADms/U0hLIJSLcgarlUyUyU; path=/; Domain=.contentful.com
< Set-Cookie: incap_ses_452_673446=3Le2eIAL4lFWojKbO9RFBmWlcFkAAAAAL3xjHbjtBskSSA8CsjySbQ==; path=/; Domain=.contentful.com
< X-Iinfo: 1-22199480-22199519 NNNN CT(75 426 0) RT(1500554597192 136) q(0 0 5 -1) r(6 6) U5
< X-CDN: Incapsula
< 
* Connection #0 to host api.contentful.com left intact
```

There is no error and the responses are as expected and documented. Why are the assets not being processed in the Contentful CMS?

Thanks in advance,

Charlie Vieillard

**Comment by Khaledgarbaya** [comment]
hi @Charl13 
did you try the [`space. createAssetFromFiles `](https://contentful.github.io/contentful-management.js/contentful-management/3.9.2/ContentfulSpaceAPI.html#.createAssetFromFiles) helper. this will return a promise that resolves to an asset and make sure to call `.publish()` on the received asset to make it public

**Comment by Charl13** [comment]
Good notice that I haven't mentioned the publishing part.

First of all the HTTP request that should process the _Asset_ doesn't seem to process it because the Contentful CMS states the following: _Cannot publish until processing has finished_.

Second, yes we've tried to publish the _Asset_ but this failed with the message _The property \"url\" is required here_ and _HTTP/1.1 422 Unprocessable Entity_.

 Please see the below cURL command we've used to publish the _Asset_.

```
charlie@XKEYSCORE-WEB-SERVER:/var/www/reactnative$ curl -v -s -X PUT -H "Authorization: Bearer <TOKEN>" -H "X-Contentful-Version: 1" https://api.contentful.com/spaces/<SPACE ID>/assets/70QFpOwagEmuMECiCEKs22/published
*   Trying 149.126.74.254...
* Connected to api.contentful.com (149.126.74.254) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: incapsula.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=Delaware,L=Dover,O=Incapsula Inc,CN=incapsula.com
* 	 start date: Mon, 03 Jul 2017 01:31:49 GMT
* 	 expire date: Fri, 03 Nov 2017 11:22:23 GMT
* 	 issuer: C=BE,O=GlobalSign nv-sa,CN=GlobalSign CloudSSL CA - SHA256 - G3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> PUT /spaces/<SPACE ID>/assets/70QFpOwagEmuMECiCEKs22/published HTTP/1.1
> Host: api.contentful.com
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer <TOKEN>
> X-Contentful-Version: 1
> 
< **HTTP/1.1 422 Unprocessable Entity**
< Access-Control-Allow-Headers: Accept,Accept-Language,Authorization,Cache-Control,Content-Length,Content-Range,Content-Type,DNT,Destination,Expires,If-Match,If-Modified-Since,If-None-Match,Keep-Alive,Last-Modified,Origin,Pragma,Range,User-Agent,X-Http-Method-Override,X-Mx-ReqToken,X-Requested-With,X-Contentful-Version,X-Contentful-Content-Type,X-Contentful-Organization,X-Contentful-Skip-Transformation,X-Contentful-User-Agent
< Access-Control-Allow-Methods: DELETE,GET,HEAD,POST,PUT,OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Etag
< Access-Control-Max-Age: 1728000
< Content-Type: application/vnd.contentful.management.v1+json
< Date: Thu, 20 Jul 2017 13:46:34 GMT
< Server: Contentful
< Strict-Transport-Security: max-age=15768000
< X-Content-Type-Options: nosniff
< X-Contentful-RateLimit-Hour-Limit: 36000
< X-Contentful-RateLimit-Hour-Remaining: 35985
< X-Contentful-RateLimit-Reset: 0
< X-Contentful-RateLimit-Second-Limit: 10
< X-Contentful-RateLimit-Second-Remaining: 9
< X-Contentful-Request-Id: 50ec40e1433383fd07ea27f3195e1735
< Content-Length: 400
< Connection: keep-alive
< Set-Cookie: visid_incap_673446=O210WM0RR5at+OZTXb3oC+mzcFkAAAAAQUIPAAAAAADB8pygolVJFTMItjVZaaaf; expires=Fri, 20 Jul 2018 07:55:45 GMT; path=/; Domain=.contentful.com
< Set-Cookie: nlbi_673446=dgVQE8bWxQPx5f8t6lKYhQAAAACNIsW7OEVOD04bZaO8BoV/; path=/; Domain=.contentful.com
< Set-Cookie: incap_ses_452_673446=1t3kZrIYXUPHGlabO9RFBjq0cFkAAAAAdATBvc3GsgON4LOqgnvuPw==; path=/; Domain=.contentful.com
< X-Iinfo: 10-46659339-46659392 NNNN CT(0 0 0) RT(1500558394028 485) q(0 0 0 12) r(2 2) U5
< X-CDN: Incapsula
< 
{
  "sys": {
    "type": "Error",
    "id": "ValidationFailed"
  },
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "required",
        "path": [
          "fields",
          "file",
          "en-GB",
          "url"
        ],
        "details": "The property \"url\" is required here"
      }
    ]
  },
  "requestId": "50ec40e1433383fd07ea27f3195e1735"
}
* Connection #0 to host api.contentful.com left intact
```

**Comment by Charl13** [comment]
Also using `ceateAssetFromFiles()` throws an exception with the following message.

> "One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant."

We've used the following code. Note that, at `fields.file.file` the variable `blob` is an instance of `Blob`.

```
	  c = createClient({ accessToken: '<TOKEN>'})
	  c.getSpace('<SPACE ID>').then((space) => space.createAssetFromFiles({
		fields: {
		  file: {
			'en-GB': {
			  contentType: 'image/jpeg',
			  fileName: '680380420.jpg',
			  file: blob
			}
		  }
		}
	  }))
	  .then((asset) => asset.processForAllLocales())
	  .then((asset) => asset.publish())
	  .then((asset) => console.log(asset))
	  .catch(console.error)
```

Anyway, we prefer getting our Asset processed with the cURL commands before taking this into Javascript.

**Comment by Khaledgarbaya** [comment]
Hi @Charl13 The processing of the asset may be not instance in some cases, what the js SDK is doing it keeps polling until it receives a processed asset with a timeout of course and  you should do the same with you cURL commands

**Comment by Charl13** [comment]
It seems the problem starts at the first HTTP request creating the _Upload_ entry. Instead of using the flag `-d/--data` we've used the flag `--data-binary`. Then on the last call (publishing the entity) the error message changes from _The property \"url\" is required here_ to _VersionMismatch_.

Now changing the request header in the last HTTP request (publishing the entity) from `X-Contentful-Version: 1` to `X-Contentful-Version: 2` will result in succes. See the below cURL command.

charlie@XKEYSCORE-WEB-SERVER:/var/www/reactnative$ curl -v -s -X PUT -H "Authorization: Bearer <TOKEN>" -H "X-Contentful-Version: 2" https://api.contentful.com/spaces/<SPACE ID>/assets/4dN4PdQ84MEiEsgumAoos0/published
*   Trying 149.126.74.254...
* Connected to api.contentful.com (149.126.74.254) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: incapsula.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=Delaware,L=Dover,O=Incapsula Inc,CN=incapsula.com
* 	 start date: Mon, 03 Jul 2017 01:31:49 GMT
* 	 expire date: Fri, 03 Nov 2017 11:22:23 GMT
* 	 issuer: C=BE,O=GlobalSign nv-sa,CN=GlobalSign CloudSSL CA - SHA256 - G3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> PUT /spaces/<SPACE ID>/assets/4dN4PdQ84MEiEsgumAoos0/published HTTP/1.1
> Host: api.contentful.com
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer <TOKEN>
> X-Contentful-Version: 2
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Accept,Accept-Language,Authorization,Cache-Control,Content-Length,Content-Range,Content-Type,DNT,Destination,Expires,If-Match,If-Modified-Since,If-None-Match,Keep-Alive,Last-Modified,Origin,Pragma,Range,User-Agent,X-Http-Method-Override,X-Mx-ReqToken,X-Requested-With,X-Contentful-Version,X-Contentful-Content-Type,X-Contentful-Organization,X-Contentful-Skip-Transformation,X-Contentful-User-Agent
< Access-Control-Allow-Methods: DELETE,GET,HEAD,POST,PUT,OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Etag
< Access-Control-Max-Age: 1728000
< CF-Space-Id: cpoizv70wn2a
< Content-Type: application/vnd.contentful.management.v1+json
< Date: Thu, 20 Jul 2017 14:25:08 GMT
< ETag: "9dcaa0b3dfed2855383a5eb5e504d864"
< Server: Contentful
< Strict-Transport-Security: max-age=15768000
< X-Content-Type-Options: nosniff
< X-Contentful-RateLimit-Hour-Limit: 36000
< X-Contentful-RateLimit-Hour-Remaining: 35973
< X-Contentful-RateLimit-Reset: 0
< X-Contentful-RateLimit-Second-Limit: 10
< X-Contentful-RateLimit-Second-Remaining: 9
< X-Contentful-Request-Id: 0c163e195c4c7929ed23331269daeef4
< Content-Length: 1346
< Connection: keep-alive
< Set-Cookie: visid_incap_673446=uEgO/p3LT5mKj5SDL+50fkS9cFkAAAAAQUIPAAAAAAAigvhxIu5fbjlBBbFIECjc; expires=Fri, 20 Jul 2018 07:55:40 GMT; path=/; Domain=.contentful.com
< Set-Cookie: nlbi_673446=1zF1QMyFrijeR8vW6lKYhQAAAACi00uAL2AmAiMZRlzvsKAk; path=/; Domain=.contentful.com
< Set-Cookie: incap_ses_452_673446=PhUGHq+qEjZwQHObO9RFBkS9cFkAAAAAF3T4OBe1b721mHXU0MV/TA==; path=/; Domain=.contentful.com
< X-Iinfo: 0-19710016-19710053 NNNN CT(0 0 0) RT(1500560708173 156) q(0 0 0 -1) r(2 2) U5
< X-CDN: Incapsula
< 
{
  "fields": {
    "title": {
      "en-GB": "My cute cat pic"
    },
    "file": {
      "en-GB": {
        "contentType": "image/jpeg",
        "fileName": "680380420.jpg",
        "details": {
          "image": {
            "width": 1024,
            "height": 767
          },
          "size": 509264
        },
        "url": "//images.contentful.com/<SPACE ID>/4dN4PdQ84MEiEsgumAoos0/45727b0ce1a68e9b14d0a25ce6821f7b/680380420.jpg"
      }
    }
  },
  "sys": {
    "id": "4dN4PdQ84MEiEsgumAoos0",
    "type": "Asset",
    "createdAt": "2017-07-20T14:23:50.214Z",
    "createdBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "3Q1HvKZp4FmLhq4Vpm8fOe"
      }
    },
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "<SPACE ID>"
      }
    },
    "version": 3,
    "updatedAt": "2017-07-20T14:25:08.534Z",
    "updatedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "3Q1HvKZp4FmLhq4Vpm8fOe"
      }
    },
    "firstPublishedAt": "2017-07-20T14:25:08.534Z",
    "publishedCounter": 1,
    "publishedAt": "2017-07-20T14:25:08.534Z",
    "publishedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "3Q1HvKZp4FmLhq4Vpm8fOe"
      }
    },
    "publishedVersion": 2
  }
}
* Connection #0 to host api.contentful.com left intact

This means, when the first HTTP request (creating the _Upload_) is not valid the last request publishing the _Asset_ will generate a misleading error with the message _The property \"url\" is required here_.

**Comment by Charl13** [comment]
Also the CMA documentation at publishing the _Asset_ is wrong. It describes the header `X-Contentful-Version: 13` should be used. We've succeeded with `X-Contentful-Version: 2`.

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/asset-processing

**Comment by Khaledgarbaya** [comment]
The `X-Contentful-Version: 13` is just an example, the main thing is version needs to be greater every time you perform an action on the entity
