### ISSUE TITLE
please add an example of entry.getMany with some filters on fields

### ISSUE THREAD

**Issue by RezaRahmati** [contentful/contentful-management.js#1277]
Please add an example of `entry.getMany` with filters on some fields, almost there is no example on the web, neither couldn't find any unit test regarding to it in the repo so I can see some examples of it, especially what should be passed to `select` params, or what should be passed as dynamic properties for BasicQueryOptions

```
export interface QueryOptions extends BasicQueryOptions {
    content_type?: string;
    include?: number;
    select?: string;
}
export interface BasicQueryOptions {
    skip?: number;
    limit?: number;
    [key: string]: any;
}
```

**Comment by marcolink** [comment]
Hi @RezaRahmati 👋 

For querying entries on the content management API, I suggest looking at [the docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator) of the content delivery API, as the same filters apply.  

The current [beta](https://github.com/contentful/contentful.js/tree/beta-v10/lib/types/query) for contentful.js has a predefined set of typescript definitions for queries. This might help to better understand what's possible and how to use them.

**Comment by marcolink** [comment]
Closing this for now as there hasn't been any activity in a while and we assume
you were able to solve it at hand.

But feel free to reach out again if you have more questions.

Cheers

**Comment by RezaRahmati** [comment]
Thanks, yes I figured it out, I ended up like this

```
const select = [
        'sys.id',
        'fields.slug',
        'fields.title',
        'fields.id',
        'fields.category',
        'fields.author',
        'fields.picture',
        'fields.cookingDuration',
        'fields.notes',
        'fields.description',
        'fields.howManyPeople',
        'fields.rate',
        'fields.totalRates',
        'fields.viewCount',
    ].join(',');
    
await entry.getMany({
    query: {
        skip: 100,
        limit: 10,
        content_type: 'x',
        include: 2,
        select: select,
        {
           'fields.state': "Active",
           'fields.category.sys.id': dto.category ,
           'fields.cookingDuration[lte]': dto.duration,
           'fields.cookingDuration[gt]': 0
        }
    });
```
