### ISSUE TITLE
You have exceeded the rate limit of this Space by making too many API requests within a short timespan.

### ISSUE THREAD

**Issue by rgcunha** [contentful/contentful-management.js#1286]
Hi,

We have created a script to delete all entries of a certain content type using version 9.1.2 of this library. We also replaced the default log handler to prevent logging the rate limit warnings.

While executing the script we encountered the following error:

>You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.

According to your documentation, the library should be able to re-try the request when a 429 occurs therefore this error shouldn't appear in the first place

**Comment by rgcunha** [comment]
For whoever is interested, we were making almost 1000 calls in parallel which contentful can't obviously handle.

So replacing the parallel calls with a sequential loop worked for us.

Another option is to delete entries in batches, say for example 10 in parallel at a time, to minimise getting 429's.

I had higher hopes for the throttling mechanism, but unfortunately it didn't seem to help us or we didn't get the mechanism.

**Comment by ChazUK** [comment]
@rgcunha Do you mind sharing some of your code? I'm trying to create entries as part of a migration script but having some issues with rate limiting

**Comment by marcolink** [comment]
Hi @rgcunha, 
While the library can fire retries on rate-limited calls, you can still exceed the rate limit by parallel calls. 
Your approach of sequentially executing calls is the right approach. The beta `throttling` parameter didn't work as expected for now, so you still have to handle it on your own.

**Comment by ChazUK** [comment]
For anyone coming across this I did this.

```
const client = contentful.createClient(
  {
    accessToken: process.env.CONTENTFUL_MANAGEMENT_API_KEY!,
  },
  {
    type: "plain",
    defaults: {
      spaceId: process.env.CONTENTFUL_SPACE_ID,
      environmentId: process.env.CONTENTFUL_ENVIRONMENT,
    },
  }
);

async function importer() {
  const entryFields = [...];
  const contentTypeId = "content_type";

  for (const entryField of entryFields) {
    const entry = await client.entry.create(
      { contentTypeId },
      {
        fields: entryField
    );

    console.log(`Created: ${entry.sys.id}`);
  }
}

importer();
```

You can also add something to publish in this loop.

**Comment by ChazUK** [comment]
@marcolink Although now I'm haivng trouble finding any documentation for the Plain Javascript API.

**Comment by jensbodal** [comment]
There's docs here https://contentful.github.io/contentful-management.js/contentful-management/10.26.0 and the general docs here https://www.contentful.com/developers/docs/references/content-management-api/

I'm trying to account for the rate limiting issue as well for a separate type of call, also the logHandler doesn't seem to be used for these logs:

```
{
  "sys": {
    "type": "Error",
    "id": "RateLimitExceeded"
  },
  "message": "You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.",
  "requestId": "xxxx"
}
```
