### ISSUE TITLE
Missing documentation on Creating/Updating Entries' Link fields

### ISSUE THREAD

**Issue by sdellis** [contentful/contentful-management.js#133]
Perhaps I'm missing it, but there doesn't seem to be any documentation in the [Content Management API docs](https://www.contentful.com/developers/docs/references/content-management-api) or [Contentful-management.js SDK docs](https://contentful.github.io/contentful-management.js/contentful-management/3.10.0/index.html) with regard to Creating or Updating "Link" fields. 

I have a Photo Gallery app, and I can create a comment like this: 
``` 
client.getSpace(space_id)
  .then((space) => space.createEntry('remark', {
    fields: {
      commentText: {
        'en-US': 'some comment'
      },
      name: {
        'en-US': 'Bob'
      }
    }
  }))
  .then((entry) => console.log(entry))
  .catch(console.error)
```
But when I try to send the id for a linked Entry (the photo the comment is referring to):
```
{
    fields: {
      commentText: {
        'en-US': 'some comment'
      },
      name: {
        'en-US': 'Bob'
      },
      commentImage: {
        'en-US': { id: '4MA2xHUeLeKaAs2K4Kqiog' }
      }
    }
  }
```
I get errors:
```
Error: {
  "status": 422,
  "statusText": "Unprocessable Entity",
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "unknown",
        "path": [
          "fields",
          "commentImage",
          "en-US",
          "id"
        ],
        "value": "4MA2xHUeLeKaAs2K4Kqiog",
        "details": "The property \"id\" is not allowed here."
      }
    ]
  },...
```
Obviously the object is not structured properly, but where can I find an example of the correct object structure?

**Comment by axe312ger** [comment]
Since we just pass the object to the API, you have to follow the same structure as the regular docs propose: https://www.contentful.com/developers/docs/concepts/links/

Should be sth like: (not tested)
```
{
  fields: {
    commentText: {
      'en-US': 'some comment'
    },
    name: {
      'en-US': 'Bob'
    },
    commentImage: {
      'en-US': {
        sys: {
          type: 'Link',
          linkType: 'Entry',
          id: '4MA2xHUeLeKaAs2K4Kqiog' 
        }
      }
    }
  }
}
```

**Comment by dirkbonhomme** [comment]
Thanks a lot @axe312ger, that worked for me.

Please include this example in the documentation. I'm really starting to like Contentful but the documentation definitely needs some work. Both the documentation on your site as the SDK (Node,js in my case).

A real life example is often so much more useful than a 100 like description of how the data is structured.

**Comment by etoref** [comment]
Hi there!
How can we remove a link from an existing entry, using the management API?
Not sure if this information is somewhere, but I couldn't find.
Thanks a lot.

**Comment by Khaledgarbaya** [comment]
```js
client.getSpace(space_id)
  .then((space) => space.getEntry('id')))
  .then((entry) => {
    delete entry.fields.mylinkedField
    return entry.update()
  })
  .catch(console.error)
```

**Comment by etoref** [comment]
Exactly what I needed.
Thanks @Khaledgarbaya!
