### ISSUE TITLE
Get published version of an Entry using Content Management Api

### ISSUE THREAD

**Issue by JuliaFerrandiz** [contentful/contentful-management.js#1419]
Hi,

I am building a Contentful App for a given contentful type and I need to check all the existing entries of this type for a validation. For that, I need the published version of the entries, no the Changed one.

In the EntryEditor.tsx, I have available the sdk (EditorExtensionSDK) and the cma (PlainClientAPI). To get all teh published entries, I could use ` sdk.space.getPublishedEntries({'content_type': "myContentType"})`, but I get the warning that it will be deprecated:
`since version 4.0.0 Consider using cma.entry.getMany instead See [https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/#using-the-contentful-management-library] for more details`

If I try to use the CMA, I couldn't find a way to get the published version of the entries. The best I was able to do is:
```
cma.entry.getMany({
        query: {
          content_type: "myContentType",
          'sys.publishedVersion[exists]': true
        },
      })
```

Is there a way to do it?

**Comment by Spring3** [comment]
Hey @JuliaFerrandiz . Please find the new function in the recent release (you can check the version in the PR linked in this thread)
