### ISSUE TITLE
How to perform validations when create new entry?

### ISSUE THREAD

**Issue by EddiG** [contentful/contentful-management.js#143]
We have a field that should accept only URLs (see attachment). When we do `createEntry` and send the value like `test url` for this field, we expect the validation error but getting newly created entry and no any errors. In Contentful CMS we see that the invalid value set for the field. 

How can we perform validations on `createEntry` step and avoid invalid data in the field?

![screenshot from 2017-10-09 10-43-48](https://user-images.githubusercontent.com/4124316/31326362-fba9198a-acdf-11e7-9bc8-08594e5803a0.png)

**Comment by Khaledgarbaya** [comment]
Hi @EddiG,

The validation kicks in only when publishing an entry

```js
const contentful = require('contentful-management')

const client = contentful.createClient({
  accessToken: '<content_management_api_key>'
})

client.getSpace('<space_id>')
.then((space) => space.getEntry('<entry_id>'))
.then((entry) => entry.publish())
.then((entry) => console.log(`Entry ${entry.sys.id} published.`))
.catch((err)=> console.log('validation error', err))
```

**Comment by EddiG** [comment]
Thank you @Khaledgarbaya 

So, if we don't want to publish but only validate we should perform `entry.publish()` and then `entry.unpublish()`? 

Would be great to have the distinct property or method for this, like `entry.isValid` or `entry.validate()`.

**Comment by Khaledgarbaya** [comment]
Hi @EddiG,
You don't need to do that, ContentTypes has a `sys.validations` property which can help you perform the validation client side.
You can get contentTypes and check your data for each field and then allow the user to create them or not

**Comment by EddiG** [comment]
We have not found any information about how we can access this property in the docs. We tried to get the entry from `space.getEntry` but there no validations property in `sys`, `sys.contentType`, `sys.contentType.sys` or in any of fields of the entry. Can you provide some links or examples about how we should access and use it, please?

**Comment by Khaledgarbaya** [comment]
Hi @EddiG,
You need to get the contentType, using `space.getContentType('<contenttype-id>')`

**Comment by EddiG** [comment]
Thank you @Khaledgarbaya now we see the validations. That is how it looks
```
[ 
{ unique: true },
  { regexp: 
     { pattern: '^(ftp|http|https):\\/\\/(\\w+:{0,1}\\w*@)?(\\S+)(:[0-9]+)?(\\/|\\/([\\w#!:.?+=&%@!\\-\\/]))?$' },
    message: 'URL Only' } ]
```
I don't sure that it is useful for us, but I close this issue for now.

**Comment by Khaledgarbaya** [comment]
HI @EddiG you can use that data to validate the data inside of your entry client side.

**Comment by EddiG** [comment]
I think it would be useful if we can get this validation rules from API and then apply on particular values on HTML form. For doing this, we should bind the rules from API and field on the form. Is some tool for doing this or we need to implement it? If we should implement it then we need to know all possible validation rules. Can you provide this rules for us?

**Comment by Khaledgarbaya** [comment]
You can find all possible validations here https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types/content-type. Under validation section

**Comment by EddiG** [comment]
Thank you again @Khaledgarbaya

**Comment by denar90** [comment]
There's another for handling validation before publishing content using [Bulk Action API](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/bulk-actions).

So after saving entry just call sdk. Like

```
client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment_id>'))
.then((environment) => environment.createValidateBulkAction({
    entities: {
        sys: { type: 'Array' },
        items: [
            { linkType: 'Entry', type: 'Link', id: '<entry_id>' },
            { linkType: 'Asset', type: 'Link', id: '<asset_id>' }
        ]
    }
```


Yes, it will allow user to create new entry, but after it is created proper validation might be applied and user can change value to valid one. 
Also, keep in mind that replicate Contentful validations on your own side is too complex and just using API for that with proper UX/Ui solution might be useful.
