### ISSUE TITLE
Version Missmatch when trying to patch

### ISSUE THREAD

**Issue by RichardMEN11** [contentful/contentful-management.js#1461]
I want to update the content of a field with the manangement api in a project bootstrapped with create-contentful-app. The problem is that I do not know why I am getting a 'version missmatch' from contentful when doing: 

```javascript
 await cma.entry.patch({ entryId: '6Dq8DYq4dQkNurA2cNNqgv' }, [
        {
          op: 'replace',
          path: '/fields/title/de',
          value: 'test',
        },
      ]);
```

The X-Contentful-Version should be correctly set from the librarie as quoted here: https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/updating-and-version-locking

Thanks a lot in advance! :-)

**Comment by luizfonseca** [comment]
Hi @RichardMEN11, since you are using the `PlainClient` api, you need to pass the `version` property as well when you are calling this function.

Reference: https://github.com/contentful/contentful-management.js/blob/9655c6ebca0918cf6a0db512059840483da524bd/lib/adapters/REST/endpoints/entry.ts#L48
