### ISSUE TITLE
Total items count

### ISSUE THREAD

**Issue by nenadg** [contentful/contentful-management.js#1465]
Hi, 
is there a method that will return the total items count. I'm having a problem once the total number of items in response reach the response limit. So I would need total number of items to implement paging-like behavior.

```{
  sys: { type: 'Error', id: 'BadRequest' },
  message: 'Response size too big. Maximum allowed response size: 7340032B.',
  requestId: 'blahblah'
}

**Comment by Spring3** [comment]
Hey @nenadg . It is a bit unclear what exactly request you are sending, but usually, you should be able to get the total number if you add `?limit=0` to the request. Then you will not hit the response size limit, because the response will not have any data, but also you should be able to see the total number of entities you are trying to fetch

**Comment by nenadg** [comment]
Hi @Spring3, sorry for not reaching earlier. I'm using `contentful-management`, so in the end my request would look something like this:
```
await client.getEntries({
      
      content_type: contentType,
      /* ... what else goes here to get total items count? */
    })
```
I've tried setting `limit: 0` but that didn't yield total number of entries.
Thanks!

**Comment by Spring3** [comment]
I have made some quick requests and I got the total number of entries without all the data for each entries.

For a specific content type:
<img width="888" alt="Screenshot 2022-10-26 at 21 29 58" src="https://user-images.githubusercontent.com/4171202/198119568-27277b91-b859-4c21-95ea-b33383e8ad11.png">

Total amount of entries no matter the content type
<img width="856" alt="Screenshot 2022-10-26 at 21 32 55" src="https://user-images.githubusercontent.com/4171202/198119687-1eb29d0c-c8ab-4734-bad2-513fbc748b02.png">

**Comment by nenadg** [comment]
Thanks, this resolves my issue.
