### ISSUE TITLE
not compatible with typescript 4.8.4

### ISSUE THREAD

**Issue by terryxsq** [contentful/contentful-management.js#1493]
when having typescript 4.8.4 getting following errors:
```
../../node_modules/contentful-management/dist/typings/contentful-management.d.ts(52,41): error TS2313: Type parameter 'T' has a circular constraint.
../../node_modules/contentful-management/dist/typings/contentful-management.d.ts(52,92): error TS2536: Type 'number' cannot be used to index type '{ [K in keyof T]: { [x: string]: "workflows"; }; }'.
../../node_modules/contentful-management/dist/typings/contentful-management.d.ts(54,15): error TS2313: Type parameter 'P' has a circular constraint.
```
however it is all fine with typescript 4.2.4

**Comment by aliwatters** [comment]
Same issue.

```
$ npx tsc --version
Version 4.8.4

package.json:    "contentful-management": "^10.16.0",

node_modules/contentful-management/dist/typings/contentful-management.d.ts:52:92 - error TS2536: Type 'number' cannot be used to index type '{ [K in keyof T]: { [x: string]: "workflows"; }; }'.

 52 declare function createClient<T extends (ReadonlyArray<string> | readonly ['workflows']) & {
                                                                                               ~
 53     [K in keyof T]: {
    ~~~~~~~~~~~~~~~~~~~~~
...
 55     };
    ~~~~~~
 56 }[number]>(params: ClientOptions, opts: {
    ~~~~~~~~~

node_modules/contentful-management/dist/typings/contentful-management.d.ts:54:15 - error TS2313: Type parameter 'P' has a circular constraint.

54         [P in K]: 'workflows';
```

**Comment by Spring3** [comment]
@Chaoste could it be something you could delegate to someone from your team?

**Comment by Chaoste** [comment]
I failed to find a generic solution to this problem but at least this will work for now:
https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAwgNgSwgO2AQQAoEkoF4oDeAvgFCiRQZwCGCy8SqmO+BUYNdAXFAOwDMUUuWho4YABbUqteohTpseQu07IeAgDRQA7gHsATgGsAZnD06AzjwAsAJiEknJgK7IAxsAR7kUdwYhqYAgGBQAKAEoeUKZsElcPLx8-AKCQ+VQwkigoPTBga0JsnKgRHgByDlly4tIoyjUYxSx4t09vX39A4KaAHmKAegGoAHkDBABzOmo4OBBtHWgXSwgAEyhqKABbain3KAgADzAAy0sOqBMDPS2oCQgAnglgYDBrIctgancjPQA3B5mCwAOncNwG1AGAFZeABOKEADhsUIAjAMbAiUQA2WH8AAMg2GACVJs8oMgLFAEMBypZLghDmtSnpShIEHTLJB3AgTAh9tQDAZqCBigAVA6HYLIVZ0gDa5X0xiBVnKAF0SAA+LI5PIFHgEYo5MpQSpqGolDbiKQAMW6LlOPFFtRI9TEkmkjQyzVaiQuXTSTW1uXyhQNFuNpuqhst7ttQXtEEKn3GyAmsvVOTqPBkdCazB97WS-p6XqDutD0ZEAH4KlU6OaSjNY3bTjWoMm6GmM0JlMQXdEvcwoAAfBqyPNKUduqQ5uSMZpFHIBYD23zEDZ06jIEWkEhDWCDuJg5CfUqJ4Ao5TF9LzyIAbj3w1nE5ax9PwU+Dnw18DbAjdeQcohAiB992nD1x0PV8fHfc9BG-VIS1vP9wAgWszW0JsbRbRMeHlRVTHMFVVWA0DhnA58oKgABaKBrSwAANABZABRHgSQmMkKR0KkaTpSj53zN9gDPT4bCvRCb3CFDIHQ6pMKtag4xXB0oHlEw9D0cptAVQxCIsSxtJNAAjAU1VIx8x1zKCSGE0TgChCTuikzIZLQk0AKMrClJwwp1M0ozylMgxzKIECgA

Will file the PR asap and let you know :)
