### ISSUE TITLE
Hacktoberfest participation 

### ISSUE THREAD

**Issue by ElizPN** [contentful/contentful-management.js#1496]
I would be happy to contribute to this repo.  
 Please add this repo to Hacktoberfest 2022!

Would be nice if this repo is participating to hacktoberfest if you can add this label.

https://www.digitalocean.com/blog/hacktoberfest-2022-your-mission-for-open-source

**Comment by mayakarabula** [comment]
Hey @ElizPN, I have added `hacktoberfest` to topics of this repository. I think it should allow for participation in hacktoberfest now :)

**Comment by Spring3** [comment]
@mayakarabula could you please double check if we allow external contributions to this repo? Asking because last time I saw an external PR, it had no "merge" button and we had to fork it and apply on our behalf
