### ISSUE TITLE
versionMismatch errors inquiry 

### ISSUE THREAD

**Issue by ranakhalil** [contentful/contentful-management.js#15]
Hi,

I am trying to update some entries from one space to the other, where the sys.ids are the same so is the Version no. However all entries respond with a version Mismatch error message. Could you please clarify what the version mismatch is referring to? Is it the entry publishedVersion or version number? Also how can we update entries without running into this error? We are trying to update fields values.

Thanks,

Rana

**Comment by macandcheese** [comment]
Old thread I know, but maybe this will help someone. This error is also returned if you are trying to upload an extension to Contentful with "contentful-extension create" and you've already uploaded an extension with that name.
