### ISSUE TITLE
No way/documentation for getting user information

### ISSUE THREAD

**Issue by hjfitz** [contentful/contentful-management.js#152]
I've been rooting through the docs for a while. I've found that we can get a UserID from an entry - `Entry.sys.createdBy.id`.

I've also seen that you can get the information of the current user - https://www.contentful.com/developers/docs/references/content-management-api/#/reference/users/user/get-the-authenticated-user/console/js

Is there anyway that I can get the information of different user based on the ID, or is this on the roadmap?

**Comment by Khaledgarbaya** [comment]
Hi @hjfitz,
Unfortunately this not possible right now. However I will transfer you request to our product team.
Best,
Khaled

**Comment by nerdess** [comment]
@hjfitz @Khaledgarbaya is there a way to retrieve the user information by user-id now? :)
