### ISSUE TITLE
bmp images aren't parsed appropriately

### ISSUE THREAD

**Issue by anthontaylor** [contentful/contentful-management.js#156]
There seems to be a difference in how bmp's are parsed. There are no file size dimensions upon uploading a bmp file image. Is this how bmp's are supposed to be handled? I couldn't find any documentation relating to this. I also uploaded the bmp file via the contentful website and it still doesn't parse right.

See image for reference:

<img width="2121" alt="screen shot 2017-12-04 at 4 39 39 pm" src="https://user-images.githubusercontent.com/6436329/33582325-e0759c8e-d911-11e7-98f9-2182f7b9c810.png">

**Comment by mariobodemann** [comment]
Hey,

sadly `bmp` is not fully supported. Only `jpg`, `png`, `webp` get the full love by our [Images API](https://www.contentful.com/developers/docs/references/images-api/#/reference/changing-formats).

For `bmp` we assume it is a general asset, not an image. So you can upload it process it, get some size information, but sadly resizing and other neat features will not work out of the box.

Greetings,
Mario

PS: I'm just chiming in from the Java ecosystem @ contentful, finding an issue close to my heart ...
