### ISSUE TITLE
Error on uiConfig.update()

### ISSUE THREAD

**Issue by paulihuhtiniemi** [contentful/contentful-management.js#1563]
`UIConfig` and `UserUIConfig` were introduced in #1415 and are documented [here](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/ui-config). I can load the `UIConfig` successfully but all calls on `update()` cause a `NotFound` error.

Example of doing an update without attempting to change anything:
```
const uiConfig = await env.getUIConfig();
await uiConfig.update(); // NotFound exception
```

Same thing happens with `UserUIConfig`.  

Version: 10.21.4

**Comment by ivo-toby** [comment]
Hi @paulihuhtiniemi,

Thanks for your report, we have deployed a fix to our backend.
