### ISSUE TITLE
Fields with null values cannot be updated

### ISSUE THREAD

**Issue by plmok61** [contentful/contentful-management.js#166]
I am working on a blog project and a new business requirement was added to show featured blog posts. To accommodate this, we added a boolean field to our `blog-post` content model called `featured`.

We then attempted to update all the posts to set their featured values to `false` but the field was not returned with `const posts = await space.getEntries({ content_type: 'blog-post' });`.

After reading [this thread](https://github.com/contentful/contentful.swift/issues/85) it seems like this is the default behavior for null values.

I have two questions:

When a new field is added to a content model how can we update them through the API?

If there is no way to update a field with a null value, is there a way to set a default value when the new field is added?

**Comment by layonthebeech** [comment]
bump! having this issue too

**Comment by Khaledgarbaya** [comment]
Hi @plmok61 field without content gets omitted from the payload, that's the API behavior.

to set the field value you can add the key to actual data ana calla `update` on it.

```js
const posts = await space.getEntries({ content_type: 'blog-post' });
// using bluebird Promise
Promise.map(posts.items, (post) => {
  post.fields.featured = false;
  return post.update()
})
```
