### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by mrjack88** [contentful/contentful-management.js#172]
Do you guys have an ETA for the typescript definition file?

**Comment by Khaledgarbaya** [comment]
Hey @mrjack88,
Unfortunately, we don't an ETA for this, but PRs are welcome 😄 .

**Comment by lowebackstrom** [comment]
Any progress here?

**Comment by mattwexa** [comment]
Hi there, a colleague has written TypeScript bindings for a subset of the UI Extensions API and Content Delivery API. Should we open a PR? @Khaledgarbaya

**Comment by Khaledgarbaya** [comment]
Hey @mattwexa,
PRs are always welcome!

**Comment by JanSchuermannPH** [comment]
Any progress on this? It's been more than a yea, still no ETA, no progress?

**Comment by phoebeschmidt** [comment]
@JanSchuermannPH unfortunately not. PRs are always welcome :)

**Comment by michelbitter** [comment]
I will add it somewhere today because I need them too. What is the best place to upload them in your opinion? @DefinitelyTyped/DefinitelyTyped or in this repository?

**Comment by michelbitter** [comment]
It takes a little longer than I expected. This library is way bigger than I thought ;-).

**Comment by michelbitter** [comment]
I'm working on it. Hopefully, I can come up with a PR soon :)

**Comment by michelbitter** [comment]
@phoebeschmidt, @Khaledgarbaya after #221 is merged and released. This issue can be closed right?
