### ISSUE TITLE
Get previous version of an entry

### ISSUE THREAD

**Issue by denisw** [contentful/contentful-management.js#173]
I can't find a way to get a specific version of an entry rather than the latest one. Is that possible? In particular, I would like to fetch the last _published_ version of an entry rather than the latest one (which might include unpublished changes).

**Comment by geoffhardy1** [comment]
You can use getSnapshots to get details for earlier versions of an entry, however this only works in the master environment. If you try to get snapshots for an entry on a non-master environment, it will return a 404 response.

**Comment by axe312ger** [comment]
Unfortunately, getting the last published version from our API is not possible directly. As this SDK is just using the API, we have the same limitations. What you may do:

Check this out:
https://www.contentful.com/developers/docs/references/content-management-api/#/reference/snapshots

1. get all snapshots
2. iterate through them to find the published one
3. request the published one to get additional data

I opened a internal feature request to add querying to the snapshot endpoint :)


Best,
Benedikt

**Comment by axe312ger** [comment]
In case you just read the email: I edited my response!

**Comment by Khaledgarbaya** [comment]
Closing this issue, for now, please feel free to create a new one if you still have the issue
