### ISSUE TITLE
Specifying a field's appearance

### ISSUE THREAD

**Issue by kylesimmonds** [contentful/contentful-management.js#175]
When creating a content type using `environment.createContentTypeWithId()`, is it possible to specify the appearance of a field?

For example, a field called `path` that I want displayed as a slug:

```
{
  id: 'path',
  name: 'URL path',
  type: 'Symbol',
  localized: false,
  required: true,
  disabled: false,
  omitted: false,
},
```

**Comment by axe312ger** [comment]
Hey Kyle,

yes it is possible. We call this `Editor Interface`. These links should give you enough information to implement it:

https://contentful.github.io/contentful-management.js/contentful-management/5.1.4/EditorInterface.html (Check the code example)

https://www.contentful.com/developers/docs/concepts/editor-interfaces/

**Comment by kylesimmonds** [comment]
@axe312ger thanks! So after creating the content type I can update it using `getEditorInterface()` and `editorInterface.update()` correct?

Is there a way to specify the editor interface during the initial field creation? Being able to define the interface in the same object as the field attributes would seem much easier than creating then updating it

**Comment by axe312ger** [comment]
> @axe312ger thanks! So after creating the content type I can update it using getEditorInterface() and editorInterface.update() correct?

Yes :)

> Is there a way to specify the editor interface during the initial field creation? Being able to define the interface in the same object as the field attributes would seem much easier than creating then updating it
No I am sorry, due to our [UI Extensions](https://www.contentful.com/developers/docs/concepts/uiextensions/) we have to keep it separated.

**Comment by kylesimmonds** [comment]
@axe312ger no worries, thanks for the info! I got it working by chaining `getEditorInterface()` after `createContentTypeWithId()` and `contentType.publish()`
