### ISSUE TITLE
unable to find getEnviroment on space

### ISSUE THREAD

**Issue by rahulaakaram13** [contentful/contentful-management.js#1839]
trying to get the enviroment from space but keeps throwing "Resource coul not be found".

Example:

```
import * as contentful from 'contentful-management';    
const client = contentful.createClient({
      accessToken: TOKEN
      host: "cdn.contentful.com",
    })
    const main = async () => {
      const space = await client.getSpace("SPACE_ID")
      console.log('space', space);
      const env = await space.getEnvironment('master');
      console.log("Env", env);
   }
   main()
```

**Comment by rustyy** [comment]
seems like you're mixing up CMA and CDA/CPA clients? There is no need to specify the host "cdn.contentful.com" which is the Delivery API, which is accessible via [contentful.js](https://github.com/contentful/contentful.js)

**Comment by ogunsolahabib** [comment]
> seems like you're mixing up CMA and CDA/CPA clients? There is no need to specify the host "cdn.contentful.com" which is the Delivery API, which is accessible via [contentful.js](https://github.com/contentful/contentful.js)

without host in CMA, it would throw: "The access token you sent could not be found or is invalid."

**Comment by RobertMrowiec** [comment]
same issue here... no matter what, 'contentful-management.js' can't find environment for specific space, even though both of CLI and 'contentful' npm CAN

**Comment by RobertMrowiec** [comment]
@ogunsolahabib if you still have a problem here, the very possible reason is - you've got wrong TOKEN. You shouldn't use contentful access token, but CMA Personal Token @itsppal02 @rahulaakaram13 are you sure, you've used TOKEN from CMA Personal Tokens, not just Contentful Access Token? 

![image](https://github.com/contentful/contentful-management.js/assets/25043084/8218b1bf-7f51-4b38-88d4-a8a3a6baad23)

**Comment by Vinz93** [comment]
As @RobertMrowiec and @rustyy mentioned this looks like a confusion between CMA tokens and API keys usage, thanks for the accurate suggestions here folks 🙇‍♂️

I'll try to summarize it for others who might have the same confussion :) 

**CMA tokes**  are always bound to your account, with the **same permissions across your spaces and organizations.** and it are used to interact with CMA (contentful-management API) (contentful-management) , which you do when you want to manipulate your content, which might be the case for @rahulaakaram13 and @ogunsolahabib 

Now when you want to fetch your content within your app, you will need to do via our **CDA (Delivery API) (contentful.js)** using your **API Keys**

I'm closing this ticket for now, but feel free to reach out again
if you have more questions.


Best
Vincenzo
