### ISSUE TITLE
"Validations" are missing in GET /content-types

### ISSUE THREAD

**Issue by kavithra-ef** [contentful/contentful-management.js#188]
Hi,
https://github.com/contentful/contentful-management.js/issues/186#issue-354801782

I am also facing the same issue as mentioned above. The JSON preview in website contain "validations" property, but the API response doesn't have.
**API response:**

![api_reponse](https://user-images.githubusercontent.com/41180512/45356318-94e2e680-b5e0-11e8-9b5b-83b89ab76de0.png)

**Contentful JSON Preview:**
![contentful_preview](https://user-images.githubusercontent.com/41180512/45356320-957b7d00-b5e0-11e8-8902-2b5543b85459.png)

**Comment by m-bodmer** [comment]
I am also having the same issue:

**SDK version** `"contentful": "^6.1.1",`

**Node Version**: `8.*`

I can replicate the same issue with a raw cURL request:

`curl -H 'Authorization: Bearer xxxxxx' 'https://cdn.contentful.com/spaces/{SPACE_ID}/environments/master/content_types/{CONTENT_ID}'`

Expected:
```
{
  "id": "SubHeader",
  "name": "Subheader",
  "type": "Link",
  "localized": false,
  "required": true,
  "validations": [
    {
      "linkContentType": [
        "SubHeader"
      ]
    }
  ],
  "disabled": false,
  "omitted": false,
  "linkType": "Entry"
},
{
  "id": "Footer",
  "name": "Footer",
  "type": "Link",
  "localized": false,
  "required": true,
  "validations": [
    {
      "linkContentType": [
        "Footer"
      ]
    }
  ],
  "disabled": false,
  "omitted": false,
  "linkType": "Entry"
    },
}
```

Actual response:
```
{
  "id": "SubHeader",
  "name": "Subheader",
  "type": "Link",
  "localized": false,
  "required": true,
  "disabled": false,
  "omitted": false,
  "linkType": "Entry"
},
{
  "id": "Footer",
  "name": "Footer",
  "type": "Link",
  "localized": false,
  "required": true,
  "disabled": false,
  "omitted": false,
  "linkType": "Entry"
},
```

I can also see the expected response in the https://app.contentful.com/spaces/{SPACE_ID}/content_types/{CONTENT_ID}/preview JSON preview tab

**Comment by m-bodmer** [comment]
Looking into this some more, it looks like the difference is between the Content Delivery API and the Content Management API

`https://api.contentful.com/spaces/{SPACE_ID}/content_types/{CONTENT_ID}` delivers the correct response

`https://cdn.contentful.com/spaces/{SPACE_ID}/content_types/{CONTENT_ID}` delivers a different, "incorrect" response

**Comment by Khaledgarbaya** [comment]
Hey @m-bodmer That is intended you don't get the validation with the CDA API i.e using `contentful` npm package.
