### ISSUE TITLE
Setting RichText through API does not set required marks-property on nodes

### ISSUE THREAD

**Issue by lowebackstrom** [contentful/contentful-management.js#193]
### I'm submitting a...
[x] Bug

### Current behavior
When setting a rich-text field through the Management API the returning payload is not the same as when editing straight from the editor. If I leave out the `marks`-property the API will not set this, as it seems, required property. Saving the entry through app.contentful.com does.

This will for example break the `documentToHtmlString`-helper -> `node.marks.length > 0` in function `nodeToHtmlString`.

### Expected behavior
If a property is required the API should warn/throw error or perhaps set a default value?

### Recreate

Example payload for a rich-text field:
```javascript
const description = {
    nodeType: 'document',
    content: [
        {
            nodeType: 'paragraph',
            content: [
                {
                    value: 'Some text...',
                    nodeType: 'text'
                }
            ]
        }
    ]
};

entry.fields['en-US'].description = description;

entry.update();
```

**Comment by Khaledgarbaya** [comment]
Hi @lowebackstrom,
This sound weird, let me check with our backend team and get back to you

**Comment by axmachina** [comment]
Merely having a linked asset in Draft state should not cause the entire thing to fail in my humble opinion:

![image](https://user-images.githubusercontent.com/1904640/50666808-3c5a9f00-0f6b-11e9-8238-b97209b12cfc.png)

For a dev, would be nice to have some kind of flag to ignore those and skip invalid assets altogether.

**Comment by Khaledgarbaya** [comment]
Hey @axmachina,
Your error is related to the Delivery SDK and not the management SDK.
You can ignore unresolved links by setting the param `removeUnresolved: true`.

@lowebackstrom,
That was a backend issue that should be resolved by now
