### ISSUE TITLE
How does one `getEntries` with filtering, ordering combined?

### ISSUE THREAD

**Issue by seenickcode** [contentful/contentful-management.js#1970]
Hi there, I'm using typescript and I'm looking to implement the following:

```typescript
client.getEntries({
  content_type: "aValidContentType",
  "fields.aValidField[match]": "foobar",
  order: "fields.aValidNumericalField",
});
```

The SDK is a bit difficult to parse for a Typescript newbie, therefore I'm having a hard time understanding this error:

```
Argument of type '{ "fields.aValidField[match]": string; content_type: string; order: string; }' is not assignable to parameter of type 'EntriesQueries<EntrySkeletonType, undefined> | undefined'.
  Types of property 'order' are incompatible.
    Type 'string' is not assignable to type '(OrderFilterPaths<EntrySys, "sys"> | "sys.contentType.sys.id" | "-sys.contentType.sys.id")[] | (`fields.${string}` | OrderFilterPaths<EntrySys, "sys"> | ... 4 more ... | `-fields.${string}.sys.id`)[] | undefined'.

 29   return site?.contentfulClient?.getEntries({
                                                ~
 30     "fields.aValidField[match]": "foobar",
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 32     order: "aValidNumericalField",
    ~~~~~~~~~~~~~~~~~~~~~~
 33   })!;
    ~~~
```

Additionally, the Javascript SDK's documentation only cites very [trivial examples](https://www.contentful.com/developers/docs/javascript/tutorials/using-js-cda-sdk/), i.e. for *only* filtering by content type or content type with field value filtering, *not* that with ordering combined.

**Comment by marcolink** [comment]
Hi @seenickcode,
it looks like the error you posted is coming from [contentful.js](https://github.com/contentful/contentful.js) (Delivery API) and not from contentful-management.js (Management API), is it possible? if so, I'm happy to move it over to the right repo :)
