### ISSUE TITLE
Docs Incomplete / Incorrect for Publish to Environment

### ISSUE THREAD

**Issue by dtothefp** [contentful/contentful-management.js#200]
Docs for languages other than Javascript show how to `publish` entries in a specific `environment`.  For JS `environment_id` option is listed but example does not actually represent the url shown:

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entry-publishing/publish-an-entry/console/js

```
/spaces/yadj1kx9rmg0/environments/staging/entries/5KsDBWseXY6QegucYAoacS/published
```

correct example would be

```js
client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment_id>'))
.then((environment) => environment.getEntry('<entry_id>'))
.then((entry) => entry.publish())
.then((entry) => console.log(`Entry ${entry.sys.id} published.`))
.catch(console.error)
```

Took me a while to figure this out. Also, wasn't throwing an error when I was doing a publish of an `id` I had in `staging`, but `publish` was effecting the `master` environment 🤷‍♂️ 

Looks like docs are being generated from JSDOC comments so I can make a PR

https://github.com/contentful/contentful-management.js/blob/4c30557bf2cef9c3cb1df862619151156f89fcc4/lib/entities/asset.js#L172

**Comment by phoebeschmidt** [comment]
hi @dtothefp,

Apologies for the late reply. You're referring to our API docs. It's true, the code snippets show SDK code but that is actually maintained elsewhere.

By now (😅) those snippets you linked are showing the correct publish behavior. Thanks for filing a ticket!
