### ISSUE TITLE
getLocales only returns first 100 locales

### ISSUE THREAD

**Issue by jarkkosyrjala** [contentful/contentful-management.js#202]
environment.getLocales() should return all locales in space. However it only returns first 100 locales and there's no way to give "limit" or "skip" options.

To reproduce, do this in a space that has > 100 locales
```
client.getSpace(spaceId)
  .then((space) => space.getEnvironment(environmentId))
  .then(async(environment) => {

    // Get all locales from space:
    const localesResult = await environment.getLocales() 
    console.log(localesResult.items.length) // 100
  })
```

For my use case I used this workaround:
```
const fetchAllLocales = async (skip:number = 0): Promise<any[]> => {
  let locales: any[] = []

  while (true) {
    const response = await axios.get(`https://api.contentful.com/spaces/${spaceId}/environments/${environmentId}/locales?limit=1000&skip=${skip}&access_token=${managementKey}`)
    const {items, total} = response.data
    locales = locales.concat(items)
    skip += items.length

    if (skip >= total) {
      break
    }
  }

  return locales
}
```
There's a separate bug in api.contentful.com. It does respect the skip, but ignores the limit. Meaning that it also always returns 100 locales.

Using the 5.4.0 release.

**Comment by Khaledgarbaya** [comment]
Hey @jarkkosyrjala,
thanks for reporting, it appears to be a bug indeed.
we'll tackle it asap

Khaled

**Comment by phoebeschmidt** [comment]
A year ago I found out that it's hardcoded to 100 in the backend :/ this is a "feature"... the backend teams have plans to change this, unfortunately.

Closing.
