### ISSUE TITLE
jsonpatch apply patch to remove array indexes return error

### ISSUE THREAD

**Issue by pablomuro** [contentful/contentful-management.js#2020]
I'm using the `entry.patch` to update entries on contentful, but when the operation is to remove things from the array it returns an error `PatchConflictError: Value at 5 does not exist`
I guess that every remove operation changes the size of the array, and in this way on the index 5, it returns the error

I was messing around with another tools from https://jsonpatch.com/, and https://github.com/Starcounter-Jack/JSON-Patch
is the only one that was able to apply the path to remove the entries of the array and replace the value, without throwing and error

So I'm raising this issue, to see if this error is fixable, or if the lib used to patch could be changed

![image](https://github.com/contentful/contentful-management.js/assets/9666008/54c46df6-543d-40a0-81fc-696de58d0c61)

**Comment by marcolink** [comment]
Hi @pablomuro 👋 
This is actually [expected](https://datatracker.ietf.org/doc/html/rfc6902).

A simple way to solve this, is creating the operations in DESC index order.

**Comment by marcolink** [comment]
Closing this for now due to inactivity - feel free to open it again.
