### ISSUE TITLE
Upgrade axios to remove all CVE vulnerabilities

### ISSUE THREAD

**Issue by kyrielia** [contentful/contentful-management.js#2054]
Axios has a number of CVEs associated with it:
https://security.snyk.io/package/npm/axios

Contentful-management is currently using v1.4.x:
https://github.com/contentful/contentful-management.js/blob/master/package.json#L59

Axios should be updated to the latest version as soon as possible to remove all vulnerability issues.  Ideally this should be released as soon as possible.

**Comment by t-col** [comment]
fixed in `contentful-management.js` version 11.5.7 and `contentful-migration` 4.18.0, thank you for reporting @kyrielia
