### ISSUE TITLE
Wrong role policies fallback when content type doesn't exist

### ISSUE THREAD

**Issue by jesustalaveragomez** [contentful/contentful-management.js#212]
Hello,

we've discovered that CMA has an unexpected behaviour when setting policies in content types that doesn't exist.

Example:
`policies: [
...{
        "effect": "deny",
        "constraint": {
          "and": [
            {
              "equals": [
                {
                  "doc": "sys.type"
                },
                "Entry"
              ]
            },
            {
              "equals": [
                {
                  "doc": "sys.contentType.sys.id"
                },
                "myContentTypeName"
              ]
            }
          ]
        },
        "actions": [
          "publish",
          "unpublish"
        ]
      }
]`

If 'myContentTypeName' doesn't exist in the space, CMA applies this policy to ALL content types, which is a very dangerous behavoir (actually, it happened in our production spaces, making unable to our editor users to update theis contents)

Expected behavior: if content type doesn't exist, ignore policy.

Thank you.
Regards

**Comment by phoebeschmidt** [comment]
Hi @jesustalaveragomez, this is a backend issue. It's already being handled outside of this GH issue, so I will close this one.
