### ISSUE TITLE
Updating entry fails with 'X-Contentful-Version' error

### ISSUE THREAD

**Issue by umair00** [contentful/contentful-management.js#213]
I'm trying to update an entry like so:
```
client
  .getSpace()
  .then(space => space.getEntry('entryId`))
  .then((entry) => {
    entry.fields.someField = 'some new value'
    return entry.update()
  })
```

I get the following error message: 
> Error: "value" required in setHeader("X-Contentful-Version", value)

According to the docs, this should be managed by the API:
>When updating an existing resource, you need to specify its current version with the X-Contentful-Version HTTP header (this header is automatically set when using our official SDKs).

I'm also seeing these warnings (could this be the cause?):
```
Deprecated: Space.getEntry() will be removed in future major versions.

Please migrate your code to use Environment.getEntry()
```

**Comment by ydorea** [comment]
I'm trying to update the entry too, when I use the Environment API I have another problem:
```
client.getSpace(SPACE_ID)
        .then(space => space.getEnvironment(ENVIRONMENT_ID))
        .then(environment => environment.getEntry(entryId))
        .then(async entry => {
            // [...]
            return entry.update();
        }).catch(err => console.log(err));
```

Then I receive:
"TypeError: entry.update is not a function"

**Comment by ydorea** [comment]
Nevermind, it actually worked, I was moving the entry around functions and it might have misplaced its reference.

So, @umair00, you can just do as I did there.

**Comment by z3to** [comment]
I have a similar problem when using `createEntryWithId`.

```js
client.getSpace('xxx')
  .then((space) => space.getEnvironment('xxx'))
  .then((environment) => environment.createEntryWithId(xxx, id, data))
```

The error I get is `VersionMismatch` which is probably caused because the `X-Contentful-Version` is missing. And yes, In the code [here](https://contentful.github.io/contentful-management.js/contentful-management/5.11.3/create-environment-api.js.html#line308) is no version header being send.

**Comment by phoebeschmidt** [comment]
Hi @z3to,

have you tried with the latest version?

Entries returned from `createEntryWithId` are wrapped using the `wrapEntry` function in `entities/Entry.js`, which does wrap each entry with `createEntryAPI`. The version is being sent in updates. 

Please open another issue if you continue to have problems with the version number being sent.

**Comment by kruulik** [comment]
I'm experiencing the same issue as described by @umair00 
```
entry.fields.carousel = {
              'en-CA': {
                sys: {
                  type: 'Link',
                  linkType: 'Entry',
                  id: collectionId,
                },
              },
            };
            await entry.update();
```
