### ISSUE TITLE
Content management api to give all children data (includes param)

### ISSUE THREAD

**Issue by joanned** [contentful/contentful-management.js#217]
I'm trying to create a tool to view a diff of the draft/changed vs published version of a component. This component can have many child components though. When I call getEntry() for the component, I would ideally get the content of all the children like in the delivery API, instead of just the ID of the children. How can I do this? Otherwise I need to recursively call getEntry() on the children. Is there a better way?

**Comment by phoebeschmidt** [comment]
Hi @joanned,

The SDK will "resolve links" if you use the collection endpoint-- getEntries() instead of getEntry(). Unfortunately there's not a way to resolve links getting a single entry.

**Comment by brettinternet** [comment]
@phoebeschmidt I'm unable to reproduce this currently. Has the API changed recently?

```js
const fs = require("fs");
const Contentful = require("contentful-management");

const main = async () => {
  const client = Contentful.createClient({
    accessToken: "...token",
  });

  const space = await client.getSpace("space-ID");

  const env = await space.getEnvironment("master");

  const entries = await env.getEntries({
    content_type: "my-type",
    include: 10,
  });

  fs.writeFileSync("./results.json", JSON.stringify(entries));
};

main();
```

**Comment by brettinternet** [comment]
It should be noted that this is only true for `contentful` lib and not for `contentful-management`.
