### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by rahil11** [contentful/contentful-management.js#220]
I am using 5.7.1 version of Contentful-management package and I am getting below error half of the times.

<img width="645" alt="Screen Shot 2019-07-01 at 10 54 29 AM" src="https://user-images.githubusercontent.com/16183343/60412585-4fcf8580-9bef-11e9-94c3-1e805c6b0939.png">

I am providing the image file as a stream to createAssetfromFile method of ContentfulEnvironmentAPI(https://contentful.github.io/contentful-management.js/contentful-management/5.8.0/ContentfulEnvironmentAPI.html)

Any idea what may be the issue here ?

**Comment by Khaledgarbaya** [comment]
Hey @rahil11,
It would be great if you can isolate the issue in a small project and share it with me. You can use [codesandbox](https://codesandbox.io/) for example.

**Comment by fatshotty** [comment]
hi, i'm experiencing the same issue.
I follow the thread :)

**Comment by matthew-contentful** [comment]
Closing. Please reach out to support if you have more questions:
https://www.contentful.com/support/
