### ISSUE TITLE
Typings are not exported

### ISSUE THREAD

**Issue by andrew-secret** [contentful/contentful-management.js#227]
I installed the current version of `contentful-management` (`^5.10.0`). And I cannot find the typings my IDE always suggest me to install `@types/contentful-management`...

```
Could not find a declaration file for module 'contentful-management'. '/Users/jimdo/src/github/dev/contentful-upload-image/node_modules/contentful-management/dist/contentful-management.node.js' implicitly has an 'any' type.
  Try `npm install @types/contentful-management` if it exists or add a new declaration (.d.ts) file containing `declare module 'contentful-management';`ts(7016)
```

Do u have any idea or hint for me?

**Comment by andrew-secret** [comment]
maybe we need to bundle the typings in the `webpack` config?

**Comment by Khaledgarbaya** [comment]
Hi @andrew-secret the types are distributed with the npm package and not on `DefinitelyTyped`

**Comment by mattwexa** [comment]
Hi @Khaledgarbaya yet somehow the folder contentful-management in my node_modules has no "typings" folder.

```
➜  contentful-management ✗ ls -l
total 64
-rw-r--r--   1 Matthieu  staff   1077 26 oct  1985 LICENSE
-rw-r--r--   1 Matthieu  staff  14301 26 oct  1985 README.md
drwxr-xr-x  12 Matthieu  staff    384 29 aoû 17:04 dist
-rw-r--r--   1 Matthieu  staff   6203 29 aoû 17:04 package.json
-rw-r--r--   1 Matthieu  staff    737 26 oct  1985 tonic-example.js
➜  contentful-management  ✗
```

I installed version 5.10.0 which is supposed to have typings (I saw the merge request). As @andrew-secret said, perhaps it is a Webpack configuration issue?

Cheers,
Matthieu

**Comment by Khaledgarbaya** [comment]
hmm somehow they didn't end up in the npm package, let re-release again

**Comment by andrew-secret** [comment]
Thank u soo much! ❤️

**Comment by Khaledgarbaya** [comment]
Fixed, typings are there https://unpkg.com/browse/contentful-management@5.10.1/
