### ISSUE TITLE
uploadFrom field is not defined in asset typings

### ISSUE THREAD

**Issue by kingeric027** [contentful/contentful-management.js#235]
Unable to update an asset with a new uploaded file example: 
`.then(function (oldAsset) {
                              return env.createUpload(f)
                                  .then(function (newUpload) {
                                      oldAsset.fields.file['en-US'] = {
                                          fileName: f.fileName,
                                          contentType: f.contentType,
                                          uploadFrom: {
                                              sys: {
                                                type: 'Link',
                                                linkType: 'Upload',
                                                id: newUpload.sys.id,
                                              }
                                          }
                                      }
                                      return oldAsset.update()`

Need to define uploadFrom in asset.d.ts as part of assetProps

**Comment by jroehl** [comment]
Fixed by #234
