### ISSUE TITLE
Unable to getEnvironments from space

### ISSUE THREAD

**Issue by snurby7** [contentful/contentful-management.js#236]
Using the content-management api and looking at the docs `getEnvironments()` [here]( https://www.contentful.com/developers/docs/references/content-management-api/#/reference/environments/environment-collection/get-all-environments-of-a-space/console/js) there is a missing piece in the URL created. 

Per the docs the url should be `/spaces/{space_id}/environments` 

Instead what is sent dropped the `{space_id}` and instead queries to `/spaces/environments`

Using the latest package `contentful-management@5.11.2`

**Comment by jroehl** [comment]
Hi @snurby7,
are you trying to `getEnvironments` with a browser, or nodejs?

This should work (and works for me):
```
const contentful = require('contentful-management');

const client = contentful.createClient({ accessToken: '<access_token>' });
client.getSpace('<space_id>')
  .then(space => space.getEnvironment('master'))
  .then(environment => environment.getEntries())
  .then(console.log)
  .catch(console.error);
```

**Comment by snurby7** [comment]
Hey @jroehl, 

Yeah I'm running this on a little node server. 

Here's an example of how I'm trying to call it.
```js
export class ContentManager {
  private client: ClientAPI;

  constructor() {
    this.client = createClient({
      // This is the access token for this space. Normally you get the token in the Contentful web app
      accessToken: ContentfulAccessToken
    });
  }

  public async getSpaces(): Promise<Collection<Space>> {
    return this.client.getSpaces();
  }

  public async getEntriesForSpace(spaceId: string): Promise<any> {
    const space = await this.client.getSpace(spaceId);
    const environment = await space.getEnvironment("master");
    const entries = await environment.getEntries();
    console.log(entries);
    return entries;
  }
}
```

When I call `getEntriesForSpace` it still errors out for me. I tried switching my node version to 8.x and it still won't work and returns me the below (shortened a little)

```
"status": 404,
  "statusText": "Not Found",
  "message": "The resource could not be found.",
  "details": {
    "type": "Space",
    "id": "environments"
  },
  "request": {
    "url": "https://api.contentful.com:443/spaces/environments/master",
...
```

**Comment by snurby7** [comment]
All good, I made a terrible mistake higher up the chain.

**Comment by mkollers** [comment]
Can you share your "terrible mistake" - I think I am doing the same :-(

**Comment by snurby7** [comment]
> Can you share your "terrible mistake" - I think I am doing the same :-(

If I knew what it was I'd tell you, probably just some bad logic where I was calling on the wrong environment or not waiting for something, sadly I don't have access to that old code anymore :/

**Comment by KristofaJosh** [comment]
it's easy to mistakenly use the access token in Settings - API Keys (content delivery) vs Settings - CMA tokens.
Make sure to create a personal access token in contentful and use that instead
