### ISSUE TITLE
Query filtering...?

### ISSUE THREAD

**Issue by ianseyer** [contentful/contentful-management.js#24]
Hi there.

Can I get some general documentation/explanation of how queries should be executed via this module?

space.getEntries() is not fully descriptive.

As per the source code,
```
getEntries: function(object) {
    var query = Query.parse(object);
    return this.client.request('/spaces/' + this.sys.id + '/entries', {query: query})
      .then(_.partial(SearchResult.parse, this.client));
  },
```
I would like to not have to dig into what Query is or how it works myself to reverse engineer the query syntax.

Specifically, I am looking to query all entries with a linked, 'parental' resource (a contenttype of ID "campaign" in this instance) that have a particular name.
e.g. all entries where `entry.campaign.name == nameInQuestion`

**Comment by grncdr** [comment]
Hi Ian, we'll be sorting out the docs for this module real soon, but in the meantime here's a quick summary of how queries work.

The parameter to `getEntries` (and `getAssets`) is added to the request query string. The query string parameters themselves are fully documented in [the API docs](http://docs.contentfulcda.apiary.io/#reference/search-parameters) but for your case you would want to do something like this (using `async/await` syntax for brevity):

```js
let campaign = await client.getEntry({
  content_type: campaignType.sys.id,
  'fields.name': nameInQuestion
})
let campaignEntries = await client.getEntries({
  content_type: childType.sys.id,
  'fields.campaign': campaign.sys.id
})
```

**Comment by ianseyer** [comment]
Okay!

So I have a contentType called Campaign that references another called Story.

I would like to grab all Story entries that match a campaign, and a have a boolean attribute "used" set to false.

Here a snippet of what I am doing now. Is this reasonable?
```
contentfulClient.getSpace(spaceName)
      .then(function(space){
        //grab all stories from the space's campaign being donated to
        entries = space.getEntries({"content_type":"story",   "fields.campaign.fields.name":campaignName, "used":false})
        console.log("retrieved entries: " + entries)
      }
```

**Comment by grncdr** [comment]
It's close but unfortunately won't work. The API doesn't (yet) support filtering on the field values of referenced entries (the `fields.campaign.fields.name` part of the query).  You need to split it into two requests, one to get the campaign and one to get the stories.

Another possible gotcha: if your content type was created in our user interface it will have an auto generated ID, e.g. `"story"` could only be the content type ID if you created the content type via the API.

**Comment by ianseyer** [comment]
Is there a plan to set a default, perhaps, where the ID of created content type is automatically a slug of that content type's name?

**Comment by grncdr** [comment]
> Okay. I'm assuming some sort of includes is in the works to include first-level relations in queries?

This exists already for our [Delivery API][include-docs], and we have discussed adding the same behaviour to the Management API but haven't yet committed to doing so. In general you don't want to serve web traffic from the Management API as the rate-limits are significantly lower.

> Is there a plan to set a default, perhaps, where the ID of created content type is automatically a slug of that content type's name? This seems like a hugely beneficial feature that would be very easy to implement.

Yes, this is something we plan to do.

> Alternatively, for my situation in particular, is there a way to grab "child" elements? Grabbing the campaign first will not help me; even if I have the campaign, I need to grab stories that exclusively have relation to that campaign.

This is already possible, and what I was showing with my first example. However, I see now that I made a mistake in my first reply, so if you had tried those queries they would have failed. While you can't query into `fields` in related items, `sys.id` can be queried. That is, you can write this query:

`space.getEntries({ content_type: storyType, 'fields.campaign.sys.id': campaignId, used: false })`

If you only have the campaign name, then you need to query by name to find the campaign ID first:

```js
space.getEntries({ content_type: campaignType, 'fields.name': campaignName }).then(function (result) {
  if (result.items.length !== 1) {
    throw new Error('Campaign "' + campaignName + '" not found')  
  }
  return result.items[0].sys.id
}).then(function (campaignId) {
  return space.getEntries({ content_type: storyType, 'fields.campaign.sys.id': campaignId, used: false })
})
```

**Comment by ianseyer** [comment]
Ah! That makes much more sense.

Thank you.

**Comment by grncdr** [comment]
You're welcome! :smile:

Thanks for using Contentful and don't hesitate to reach out if you have more questions.

**Comment by grncdr** [comment]
You're welcome, I'll keep this issue open until we've got better examples either in or linked from the README. In the mean time please don't hesitate to reach out with any further questions.

**Comment by grncdr** [comment]
Fixed in #27

**Comment by tleunen** [comment]
@grncdr - After 2 years, is this still the case?
> The API doesn't (yet) support filtering on the field values of referenced entries (the fields.campaign.fields.name part of the query).

**Comment by grncdr** [comment]
I haven't been at Contentful for nearly 2 years, so I really don't know 🙃

Seems like @Khaledgarbaya is the primary maintainer of this library now and would be in a better position to answer your question.

**Comment by tleunen** [comment]
It's valid for the cdn library as well btw :) Thanks @grncdr!
