### ISSUE TITLE
Delete unused (NOT linked to any entry) media

### ISSUE THREAD

**Issue by w3debugger** [contentful/contentful-management.js#240]
I'm trying to delete the unused / unlinked assets. Is there something anything I can do to find media which are NOT linked to any entry?

e.g.
The media shown below has 1 entry, so It shouldn't be deleted
<img width="519" alt="Screen Shot 2019-10-24 at 11 03 08 AM" src="https://user-images.githubusercontent.com/6707482/67461228-ea941a00-f64d-11e9-9bd8-acf48e4aa4bb.png">

But the media below is NOT linked to any entry and i want to delete it
<img width="666" alt="Screen Shot 2019-10-24 at 11 07 42 AM" src="https://user-images.githubusercontent.com/6707482/67461591-bcfba080-f64e-11e9-8543-f19de0a7fc73.png">

**Comment by OriginalEXE** [comment]
Hello 👋 

You can use https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/links-to-asset/query-entries/console/js to check if any entries are linking to a specific asset.

One solution would be to loop through all the assets and check for each if anything is linking to it.

**Comment by w3debugger** [comment]
Yeah, that's what support also asked me to do 🤦‍♂ 
`10 requests / second` and  in `1 API call / 1000 assets`
I had 18000 assets and ended up having too much loops and delays for almost 20 to 30 minutes 🙄 
I wanted contentful team to provide us a simple endpoint where we can get all unlinked assets and 1 simple URL where we can send array of assetIds to archive them.

**Comment by w3debugger** [comment]
> Hello 👋
> 
> You can use https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/links-to-asset/query-entries/console/js to check if any entries are linking to a specific asset.
> 
> One solution would be to loop through all the assets and check for each if anything is linking to it.

**Comment by OriginalEXE** [comment]
I agree it would be handy as a filter on the assets collection itself.

**Comment by phoebeschmidt** [comment]
Hi folks,

This is a backend feature request, not an SDK bug. Please submit your feedback by emailing product-feedback@contentful.com or submit a ticket here https://www.contentful.com/support/

Thanks!

**Comment by DRS90** [comment]
Do we have any update on this?
