### ISSUE TITLE
Incomplete interface in AssetFileProp.fields.file

### ISSUE THREAD

**Issue by herschel666** [contentful/contentful-management.js#241]
Hi. I just tried to ditch my custom-made typings & use the ones you ship with the package. Thereby I stumbled upon the issue, that `Environment#createAssetFromFiles` expects a `data`-parameter of type [`AssetFileProp`](https://github.com/contentful/contentful-management.js/blob/213c9525bff4674f66684e927315f2b0956aff41/typings/asset.d.ts#L22), that again only expects to have a `file`-property on its `.fields.file`-interface, while [`Environment#createAssetFromFiles`](https://github.com/contentful/contentful-management.js/blob/213c9525bff4674f66684e927315f2b0956aff41/lib/create-environment-api.js#L549) clearly expects that object to have a `contentType`- & a `fileName`-property, too. But those properties are only present on the [`AssetProps.fields.file`](https://github.com/contentful/contentful-management.js/blob/213c9525bff4674f66684e927315f2b0956aff41/typings/asset.d.ts#L5)-interface.

Looks like `Environment#createAssetFromFiles`'s `data`-parameter should rather be of type `AssetProps` than `AssetFileProp`. But then again I'm not that much into the codebase to tell whether that change would break things in other places…

**Comment by OriginalEXE** [comment]
Hello, thank you for raising the issue and your PR. Most of the team is on holidays so this might be stalled for a bit longer, but rest assured we will look into it soon.
