### ISSUE TITLE
Not all TypeScript defintions are exported

### ISSUE THREAD

**Issue by Hless** [contentful/contentful-management.js#245]
Interface types like `Space`, `Environment` and `Entry` are currently not exported with the TypeScript definitions. It is possible to infer them from return types, but this is not an ideal solution of course. Perhaps it is useful to TypeScript developers to export them as well.

For those interested in how to infer the types:
```
type ExtractGeneric<Type> = Type extends Promise<infer X> ? X : never
type Client = ReturnType<typeof createClient>;
type Space = ExtractGeneric<ReturnType<Client["getSpace"]>>;
type Environment = ExtractGeneric<ReturnType<Space["getEnvironment"]>>;
```

**Comment by phoebeschmidt** [comment]
Hi @Hless ,

Recently we've made some updates to our types. For example: https://github.com/contentful/contentful-management.js/blob/4811669922ad6cd223561983f0eb805b83528cc3/typings/space.d.ts#L40
has the methods with defined return types, and the object returned is also additionally typed.

I'll close this issue but please feel free to open another one if you have more problems. PRs are also always welcome :) 

Thanks for your patience and opening an issue.
