### ISSUE TITLE
getSpaces() interface missing parameter

### ISSUE THREAD

**Issue by nickgerig** [contentful/contentful-management.js#246]
//typings/contentfulManagement.d.ts
ClientAPI.getSpaces(): Promise<Collection<Space>>

We cannot change query params as no parameter is defined in the interface.

**Comment by ruderngespra** [comment]
Hi, thank you for raising this issue.
`getSpaces()` actually does not take any parameters.
Let us know if you have any other questions!

**Comment by nickgerig** [comment]
Hi,

There is a default `limit` on the query of 25 items, whereas we have over 50 so I can't see how else we would query for items 26-50?

The underlying code supports standard Contentful query params. So for example I can do the following:

` //@ts-ignore
    const { total, skip, limit, items } = await client.getSpaces({ limit: 100 })`

**Comment by ruderngespra** [comment]
Hi, thank you very much for pointing that out! I will update the `clientSpaces` method so that its interface supports these standard contentful query parameters.

**Comment by ruderngespra** [comment]
I updated the typechecks so that `getSpaces()` should accept limit and skip as optional params now.
