### ISSUE TITLE
How to set values within the sys property?

### ISSUE THREAD

**Issue by axe312ger** [contentful/contentful-management.js#247]
I want to set the creation date of an entry as I am importing from another CMS.

Everything works great except that my values for `sys.createdAt` are ignored.

My code:

```js
contentfulNews = await environment.createEntryWithId(
  'blogPost',
  newsEntry.id,
  {
    sys: {
      createdAt: newsEntry.created,
    },
    fields,
  }
)
```

Anything I need to do to be able to alter sys.createdAt? I tried to pass a string and a JS-Date object. Both didn't work.

Thanks a lot,
Benedikt

**Comment by jroehl** [comment]
Hi Benedikt,

I am afraid that it is not possible to change the properties in `sys` directly. The `sys` property is ignored when creating the entry.

Best,
Johann

**Comment by axe312ger** [comment]
@jroehl are you sure this is limitation by the API and not just by the SDK?

The management api docs state the following: 
> Note: Once created, none of the sys properties can be changed. 

(https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/common-resource-attributes)


If you are right, I think the docs wording is misleading. Maybe even state there that these values can't be set, if so.

Best,
Benedikt

**Comment by dlitvakb** [comment]
Heya @axe312ger! Nice to see you around again!

Yup, this is something coming from the API, `sys` attributes are not something a user can set at any time, it's metadata generated by our API.

If you want to have a custom date, for example for creating publishing calendars, then you need to add one or more date fields depending on your needs for the content types you need to manage this data for.

Cheers

**Comment by axe312ger** [comment]
@dlitvakb hey ho :) still around all the timer, just as customer, not as employee 🙃 

Yeah I see and this makes actually sense.

I will use a field now for publicationDate, this also allows my editors later on to change the field as it will order the blog posts.



Just one thing:

Can you state in the management docs website, that this is api generated metadata and can not be changed? As mentioned above, I think the one sentence is misleading.

**Comment by dlitvakb** [comment]
Will forward the feedback

Thanks!
