### ISSUE TITLE
Exposing publishing schedule for an entry

### ISSUE THREAD

**Issue by westmark** [contentful/contentful-management.js#249]
Hi! Now that scheduled publishing is supported natively, are there any plans to add the schedule of an entry to its `sys` object? 

We desperately need to access this in order to appease our editors. Supplanting this feature by adding custom fields to the content type is our last resort, but then we would (obviously) reinventing the wheel.

**Comment by freakyfelt** [comment]
Hey, I'm from the team that owns the scheduled actions feature. For now there are no plans to add the scheduled actions into the `sys` for an entry. The suggested way to retrieve schedules for a particular entry is to use the scheduled actions endpoint. Currently the JS SDK doesn't have scheduled actions as a first class object, so you will need to use the client's [rawRequest](https://github.com/contentful/contentful-management.js/blob/master/lib/create-contentful-api.js#L373-L375) method for now.

```
const response = client.rawRequest({
  method: 'GET',
  url: '/space/<spaceId>/scheduled_actions?sys.environment=master&sys.status=scheduled&entity.sys.id[in]=entryId1,entryId2,entryId3'
});
```

NOTE: you can also use `entity.sys.id=entryId1` for a single entry's schedule.

Regardless this will return a response like this:

```json
{
  "sys": {
    "type": "Array"
  },
  "pages": {},
  "limit": 100,
  "items": [
    {
      "sys": {
        "id": "$scheduledActionId$",
        "type": "ScheduledAction",
        "createdAt": "2020-02-17T14:54:35.112Z",
        "createdBy": {
          "sys": {
            "id": "$userId$",
            "type": "Link",
            "linkType": "User"
          }
        },
        "space": {
          "sys": {
            "id": "$spaceId$",
            "linkType": "Space",
            "type": "Link"
          }
        },
        "status": "scheduled"
      },
      "entity": {
        "sys": {
          "id": "$entityId$",
          "linkType": "Entry",
          "type": "Link"
        }
      },
      "environment": {
        "sys": {
          "id": "master",
          "linkType": "Environment",
          "type": "Link"
        }
      },
      "scheduledFor": {
        "datetime": "2020-05-30T14:00:00.000Z"
      },
      "action": "publish"
    }
  ]
}
```

Hopefully that at least unblocks you

**Comment by freakyfelt** [comment]
Closing this issue for now. See the above for the suggested solution
