### ISSUE TITLE
New release to include source environment when creating a new environment

### ISSUE THREAD

**Issue by micksi** [contentful/contentful-management.js#258]
@phoebeschmidt (sorry for spamming)

Requesting a new release of "contentful-managent" package to include the linked commit
https://github.com/contentful/contentful-management.js/commit/3726e2671bbffcf8fe803237579152b2d0fd15f4

**Comment by phoebeschmidt** [comment]
@micksi I don't understand-- the linked commit was added a year ago (feb 2019) and I already see that code in the current release, 5.13. What am I missing?

**Comment by micksi** [comment]
@phoebeschmidt sorry for the confusion. I looked at it again and found it was just the typings that was missing the "sourceEnvironmentId" parameter which gave me the error.

Made a small PR for the fix
https://github.com/contentful/contentful-management.js/pull/259
