### ISSUE TITLE
Unable to upload asset using createAssetFromFiles

### ISSUE THREAD

**Issue by lateefbeats** [contentful/contentful-management.js#287]
Whenever I try to create a new asset using ```createAssetFromFiles``` the console throws the error " unable to locate a file for upload. This happens when copying and pasting the example straight from your docs. 
```client.getSpace('<my_space_id>')
.then((space) => space.createAssetFromFiles({
  fields: {
    title: {
      'en-US': 'Asset title'
    },
    description: {
      'en-US': 'Asset description'
    },
    file: {
      'en-US': {
        contentType: 'image/svg+xml',
        fileName: 'circle.svg',
        file: '<svg><path fill="red" d="M50 50h150v50H50z"/></svg>'
      }
    }
}})
.then((asset) => asset.processForAllLocales())
.then((asset) => console.log(asset))
.catch(console.error)
```

From the browser:
Error: Unable to locate a file to upload.
    at createUpload (create-space-api.js:799)
    at create-space-api.js:756
    at Array.map (<anonymous>)
    at Object.createAssetFromFiles (create-space-api.js:751)
    at eventForm.js:48

**Comment by matthew-contentful** [comment]
Hello,

I am not able to reproduce this issue in either a node or browser environment. Here is the fiddle I used (with valid credentials instead of placeholder strings) to test the browser case: https://jsfiddle.net/782vxwtc/

If you are still having trouble, consider reaching out to Contentful support: https://www.contentful.com/support/

**Comment by Lacka90** [comment]
@matthew-contentful using your example I got 
`Cannot publish until processing has finished`

after I extend your code with: 
`.then(asset => asset.processForAllLocales())`

I got 400 error when I go to the assets detail page on contentful website:
```
Request URL: https://images.ctfassets.net/g00z4htoeuvq/3K6Jv04NevXvohTIiwSjrs/097874563f512212d633c186cdad8a49/messi.png?w=30&h=30
Request Method: GET
Status Code: 400
```
