### ISSUE TITLE
organization.getOrganizationSpaceMemberships is not a function

### ISSUE THREAD

**Issue by swatikurra** [contentful/contentful-management.js#300]
Hi Team, 

I am seeing an issue while using getOrganizationSpaceMemberships function on the organization. 
Could you please update is this is available in the contentful management library as reference document says.

**Comment by burakukula** [comment]
Hey @swatikurra!

Thanks for letting us know. I am trying to reproduce the issue, but with no luck.

It suppose to work in the following way:

```
const contentful = require('contentful-management');

const client = contentful.createClient({ accessToken: '<access_token>' });

client.getOrganization('org_id')
  .then(org => org.getOrganizationSpaceMemberships())
  .then(items => console.log(items))
  .catch(console.error)
```

Docs are up to date in the newest version `5.21.1` - it could have been misleading before, sorry about that.
Please let me know if it's working for you when using the example or please provide more information regarding the issue (how the implementation on your side look like so I could reproduce it).

**Comment by burakukula** [comment]
Hello @swatikurra,

Any updates from your side regarding this issue?

**Comment by swatikurra** [comment]
Hey! it didn't work for me and I opted for another approach then.

**Comment by burakukula** [comment]
👋@swatikurra!

Thank you for your answer. 
Would you be able to share details of the issue? We would like to proceed with the fix if something is broken on our side. Any information, implementation details or snipped of code, regarding how the implementation on your side looked like when you faced the issue, would be very helpful for us.

thx in advance.

**Comment by suevalov** [comment]
Closing the issue due to no response from the author
