### ISSUE TITLE
Cannot find module ....

### ISSUE THREAD

**Issue by tobspeed** [contentful/contentful-management.js#301]
Hello using contenful-management with angular and i get on every "ng build" and "ng serve" the fowolling error:

`
ERROR in node_modules/contentful-management/typings/asset.d.ts:3:24 - error TS2307: Cannot find module 'stream'.

3 import { Stream } from 'stream'
                         ~~~~~~~~
node_modules/contentful-management/typings/environment.d.ts:9:24 - error TS2307: Cannot find module 'stream'.

9 import { Stream } from 'stream'
                         ~~~~~~~~
node_modules/contentful-management/typings/space.d.ts:15:24 - error TS2307: Cannot find module 'stream'.

15 import { Stream } from 'stream'
                          ~~~~~~~~
node_modules/contentful-management/typings/contentfulManagement.d.ts:1:36 - error TS2307: Cannot find module 'http'.

1 import { Agent as httpAgent } from 'http'
                                     ~~~~~~
node_modules/contentful-management/typings/contentfulManagement.d.ts:2:37 - error TS2307: Cannot find module 'https'.

2 import { Agent as httpsAgent } from 'https'
                                      ~~~~~~~
node_modules/contentful-management/typings/contentfulManagement.d.ts:4:24 - error TS2307: Cannot find module 'stream'.

4 import { Stream } from 'stream'
                         ~~~~~~~~

I still using the latest versions:
    "contentful": "^7.14.0",
    "contentful-management": "^5.19.0",

Here my complete package.json:

{
  "name": "simple-contentful-shop",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "deploy": "node deploy"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.7",
    "@angular/cdk": "^9.1.3",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/localize": "^9.0.7",
    "@angular/material": "^9.1.3",
    "@angular/platform-browser": "~9.0.7",
    "@angular/platform-browser-dynamic": "~9.0.7",
    "@angular/router": "~9.0.7",
    "@contentful/rich-text-html-renderer": "^13.4.0",
    "@ng-bootstrap/ng-bootstrap": "^6.0.1",
    "bootstrap": "^4.4.1",
    "contentful": "^7.14.0",
    "contentful-management": "^5.19.0",
    "jquery": "^3.4.1",
    "popper.js": "^1.16.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.7",
    "@angular/cli": "~9.0.7",
    "@angular/compiler-cli": "~9.0.7",
    "@angular/language-service": "~9.0.7",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  },
  "optionalDependencies": {
    "basic-ftp": "^4.5.4",
    "ftp-deploy": "^2.3.6",
    "ssh2-sftp-client": "^5.1.2"
  }
}

Any ideas or suggestions? This error prevents me from going into production, because "ng build" ist not working.
The funny thing is, despite the errors on "ng serve", locally everthings works fine and even posting/pushing something to contentful works.

**Comment by matejkramny** [comment]
Just had this issue myself. Tried to install @types/node but it has to be compiled with this project i think.

Anyway to fix your issue you can add `"skipLibCheck": true` to compilerOptions in tsconfig.json
