### ISSUE TITLE
createWebhook with secret Authorization-Bearer Token

### ISSUE THREAD

**Issue by jfarris587** [contentful/contentful-management.js#306]
https://contentful.github.io/contentful-management.js/contentful-management/5.21.1/Webhook.html#.Webhook

You can create a custom webhook with the module and have httpBasicUsername and httpBasicPassword. However, there is no option to `add a secret header` like there is in the web interface

**Comment by suevalov** [comment]
Hi @jfarris587 

We updated our type definitions for webhooks and you can pass an optional `secret: true` value to any header

https://github.com/contentful/contentful-management.js/blob/master/lib/entities/webhook.ts#L36
