### ISSUE TITLE
Issue executing clone-space.js

### ISSUE THREAD

**Issue by temelj** [contentful/contentful-management.js#31]
I am getting an error when trying to clone spaces.

```
c:\GitHub\contentful-management.js>node example\clone-space --access-token $SOURCE_TOKEN --source-space-id $SOURCE_ID --destination-access-token $DEST_TOKEN --destination-pace-id $DEST_ID --only-content-types
c:\GitHub\contentful-management.js\example\clone-space.js:77
      .spread(clone)
       ^
TypeError: undefined is not a function
    at Object.<anonymous> (c:\GitHub\contentful-management.js\example\clone-space.js:77:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
NOTE: I have removed the tokens & space ids.
```
C:\GitHub\contentful-management.js>npm version
{ 'contentful-management': '0.1.1',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

**Comment by trodrigues** [comment]
Right, we moved away from bluebird but this wasn't properly changed. Thanks for the report.

**Comment by temelj** [comment]
Will the dependency be removed with the next set of check-ins?

**Comment by skddc** [comment]
Same here. Could you please fix it? Would be much quicker for someone who knows exactly what changed.

**Comment by vbohush** [comment]
Same issue

**Comment by temelj** [comment]
We have a workaround for the issue and it works but i wouldn't rely on it 100%. See my profile it should show up under perduco\contentful-management-fix

**Comment by trodrigues** [comment]
Hi there,

we have published a new separate tool for space cloning and synchronization at https://github.com/contentful-labs/contentful-space-sync

We still need to add some options like "only content types" and host, so it can be used with preview.contentful.com, but other than that it is a more complete and reliable tool, so we are going to discontinue this script.

**Comment by vbohush** [comment]
Thanks, I already used contentful-management.js version 0.1.1 It works for me.

**Comment by skddc** [comment]
Great, thanks!
