### ISSUE TITLE
Is there any CMA method to create nested entries ?

### ISSUE THREAD

**Issue by tamils360** [contentful/contentful-management.js#313]
I want to create a nested entry. Which means an entry contains another entry and so on.
```
fields: {
    title: { 'de-DE': 'example-title', 'en-US': 'Summary' },
    slug: { 'en-US': 'example-app-summary' },
    **modules**: { 'en-US': [Object] }
  }
```
The **modules** property contains another entries meta-data shown below: 
`{sys: { type: 'Link', linkType: 'Entry', id: '<content_type>' }, fields: {...} }`
fields property also have new entry inside.

how I can create an entry with nested items? I'm not sure it is available.

**Comment by suevalov** [comment]
Hi @tamils360 

Unfortunately, we don't have such a method. We need to create entries in separately and then use their ids to link to another one.
