### ISSUE TITLE
Organization getTeams() does not exist

### ISSUE THREAD

**Issue by Rohit-007** [contentful/contentful-management.js#332]
const contentful = require('contentful-management')

client.getOrganizations()
.then((organization) => organization.getTeams())
.then((teams) => console.log(teams))
.catch(console.error)

// Response : 
TypeError: organization.getTeams is not a function

**Comment by vbeleuta** [comment]
Hi @Rohit-007,

Thank you for pointing this out. The docs were wrong and will be updated shortly. 

You can get the organization teams the following way:

```
const contentful = require('contentful-management')
const client = contentful.createClient({ accessToken: '<content_management_api_key>' })

client
.getOrganization('<orgId>')
.then((organization) => organization.getTeams())
.then((teams) => console.log(teams))
.catch(console.error)
```
