### ISSUE TITLE
Creates a Space Team membership  -- Not working

### ISSUE THREAD

**Issue by rohit-010** [contentful/contentful-management.js#339]
const client = contentful.createClient({
  accessToken: '<content_management_api_key>'
})

client.getSpace('<space_id>')
.then((space) => space.createTeamSpaceMembership('team_id', {
  admin: false,
  roles: [
    {
      type: 'Link',
      linkType: 'Role',
      id: '<role_id>'
    }
  ],
}))
.then((teamSpaceMembership) => console.log(teamSpaceMembership))
.catch(console.error)

Error --> Not accepting **team_id** as asrgument

How can i assign my created team to given space and then assign space roles using API
Thanks

**Comment by vbeleuta** [comment]
Hi @rohit-010,

The function you are looking at is the correct one to give a space access to a team. I had a look at the `createTeamSpaceMembership` function, and it should accept the `teamId` (which is the `team.sys.id`) as a first argument. (Please show us the request and error message if the issue persists.) I did see one mistake in our docs for the request payload, the roles object should be: 
```
{
  roles: [
    {
      sys: {
        type: 'Link',
        linkType: 'Role',
        id: '<role_id>'
      }
    }
  ]
}
```
The docs will be updated shortly.

You can both give a team space access and assign roles with this one request.
First make sure you get the space you want to assign the team to with:
`client.getSpace('spaceId')` 
Then once you have the space you can see all the roles the space has with the function:
`space.getRoles()` and see what is the `roleId` you need in the array that is returned.
Lastly you can assign the team with `createTeamSpaceMembership` on the space object you want the team to have access to.
```
client.getSpace('SPACEID')
   .then((space) => space.createTeamSpaceMembership('TEAMID', {
       admin: false,
       roles: [
           {
              sys: {
                type: 'Link',
                linkType: 'Role',
                id: 'ROLEID'
              }
           }
       ]
   }))
  .then((teamSpaceMembership) => console.log(teamSpaceMembership))
  .catch(console.error)
```
You can also provide multiple roles, if they are available for that space.
Make sure the access token you are using belongs to an organization member that also has access to that space.

I hope this helps.

**Comment by vbeleuta** [comment]
Typings fix merged. Thank you for pointing out the issue.
