### ISSUE TITLE
Create Org Team Membership - Not working

### ISSUE THREAD

**Issue by rohit-010** [contentful/contentful-management.js#340]
client.getOrganization('organizationId')
.then((org) => org.createTeamMembership('teamId', {
   admin: true,
   organizationMembershipId: "3ugleZJgHKk89I1P5MSDuY"
 }))
.then((teamMembership) => console.log(teamMembership))
.catch(console.error)

No option to specify TEAMID

Also want to know how can I assign users to Team via API ?

**Comment by vbeleuta** [comment]
Hi @rohit-010,

When creating a new team membership you must provide the `teamId` you want as a first argument to the function `organization.createTeamMembership`.

```
client.getOrganization('organizationId')
.then((org) => org.createTeamMembership(**'teamId'**, {
admin: true,
organizationMembershipId: "3ugleZJgHKk89I1P5MSDuY"
}))
.then((teamMembership) => console.log(teamMembership))
.catch(console.error)
```

You can assign users to a team only after inviting them to the organization and providing the `organizationMembershipId` of that user in the request payload.

If you still have trouble creating memberships please provide the request again and the error message you get.

I hope this helps!

**Comment by rohit-010** [comment]
Hello @vbeleuta ,

Thanks for your reply
I am not able to assign that TEMA_ID in code
If you refer to this issue : https://github.com/contentful/contentful-management.js/issues/339
It is similar , when trying from typescript code it is not accepting extra parameter , it is just accepting single parameter 
and that single parameter dont have option to specify TEAM_ID

In docs it is mentioned to pass TEAM_ID and which makes sense but in code it is not accepting that

**Comment by vbeleuta** [comment]
Hi @rohit-010,

Can you show me the code and error message? I just did a test with version 5.26.5 of the SDK and was able to create one.

**Comment by vbeleuta** [comment]
Hi @rohit-010, 
I think there might be an issue with the typings indeed, since I see only one argument. Similar for issue https://github.com/contentful/contentful-management.js/issues/339 Will open a pull request shortly and hopefully that will solve your issue.

**Comment by vbeleuta** [comment]
Typings fix merged.
