### ISSUE TITLE
Incorrect example 

### ISSUE THREAD

**Issue by ClareJolly** [contentful/contentful-management.js#352]
https://github.com/contentful/contentful-management.js/blob/bf07e7a413c1bb681fca3418419c6202ef80af4a/lib/entities/app-installation.ts#L56

The example code shown will actually delete the environment rather than the app installationi that should be demonstrated

example code should be updated

**Comment by suevalov** [comment]
Thanks for raising the issue @ClareJolly 👍 

We updated the example. Good spot!
