### ISSUE TITLE
How to get all Roles from a given space?

### ISSUE THREAD

**Issue by rohit-010** [contentful/contentful-management.js#359]
client.getSpace('<space_id>')
.then((space) => space.getRoles())
.then((response) => console.log(response.items))
.catch(console.error)

In above method space.getRoles() error is ,  **this method does not exist..**
Not able to get all the roles present in existing space 
Also checked interface **ContentfulSpaceAPI**  and there is no such error present in package.
Can you please fix this asap.

Thanks

**Comment by suevalov** [comment]
Hi @rohit-010!

Could you please try using v5.27.0? The issue should be fixed.

**Comment by rohit-010** [comment]
@suevalov Cool this is fixed now

Cheers
