### ISSUE TITLE
Updating space roles permissions and policies gives 503 error

### ISSUE THREAD

**Issue by rohit-010** [contentful/contentful-management.js#360]
_client.getSpace('<space_id>')
.then((space) => space.getRole('<roles_id>'))
.then((roles) => {
  roles.name = 'New role name'
  return roles.update()
})_

Above method works fine to update name and description of role
But throws 503 Server error when we try to update policies and permissions 

Is there another way to update policies and permissions  using API ?

**Comment by vbeleuta** [comment]
Hi @rohit-010, 

Could you try and see if you can update policies and permissions by using v5.27.1: https://github.com/contentful/contentful-management.js/releases/tag/v5.27.1?

**Comment by rohit-010** [comment]
Hello @vbeleuta 
Thanks for update now  able to update policies .

Cheers
