### ISSUE TITLE
Typing for 'Role' seems to be incorrect

### ISSUE THREAD

**Issue by fabbru-s2** [contentful/contentful-management.js#363]
Hi,

it looks like the type for `Role` does not seem to be correct. When comparing the [type](https://github.com/contentful/contentful-management.js/blob/master/lib/entities/role.ts) to the [documentation](https://www.contentful.com/developers/docs/tutorials/general/roles-via-api/)  you can make a few observations, e.g.:
-  `Environments` and `EnvironmentAliases` are keys of the `permissions` object but missing in the [type](https://github.com/contentful/contentful-management.js/blob/master/lib/entities/role.ts)
- `actions` in `policies` can actually be an array of strings but the [type](https://github.com/contentful/contentful-management.js/blob/master/lib/entities/role.ts) is defined as string only.

Maybe issue [360](https://github.com/contentful/contentful-management.js/issues/360) is related  to this malformed typing as well.

Cheers,
Fabian

**Comment by suevalov** [comment]
Hi @fabbru-s2! Thanks for reporting the issue. I can confirm that typings are not correct.

We'll fix it and release a new version soon

**Comment by suevalov** [comment]
Hey @fabbru-s2 👋 

The fix is available in v5.27.1: https://github.com/contentful/contentful-management.js/releases/tag/v5.27.1
