### ISSUE TITLE
Typings of Webhook is not correct

### ISSUE THREAD

**Issue by rohit-010** [contentful/contentful-management.js#365]
Hello Team,
I am using createWebhookWithId method and it is accepting two params 
 1) webhook id (string)
 2) data (WebhookProps) 
So problem is with WebhookProps 
WebhookProps has mandatory attributes like : 
      sys: MetaSysProps;
      httpBasicUsername: string;
      httpBasicPassword: string;

As I am creating webhook I wont have detail of **sys**
**httpBasicUsername** and **httpBasicPassword** -- this I dont want to use for my webhook

Can you please fix this typescript issue:
Also if I refer to your API docs example given is : 
_client.getSpace('<space_id>')
.then((space) => space.createWebhookWithId('<webhook_id>', {
  'name': 'My webhook',
  'url': 'https://www.example.com/test',
  'topics': [
    'Entry.create',
    'ContentType.create',
    '*.publish',
    'Asset.*'
  ]
}))_

So this issue is related to typings , can you please fix this asap.
Thanks

**Comment by suevalov** [comment]
HI @rohit-010,

We rewrote the core of the library to Typescript and now type definitions should be the way better.
Could you please verify that the issue is gone in `5.27.0`?

**Comment by rohit-010** [comment]
Hello @suevalov ,

Thanks for change but still few other's are not fixed 
example I want to pass secret header then it is not allowing or API is throwing error while creating new webhook

How can I pass header like : 
  _"headers": [
        {
            "key": "key",
			"value: "key-value"
            "secret": true
        }
    ]_
	
Also if I don't want to pass httpBasicUsername and httpBasicPassword, this is mandatory in current WebhookProps so can you please handle this as well.

Thanks

**Comment by rohit-010** [comment]
Hello @suevalov ,

Also I think URL is accepting as string in Typings but string is not accepted by server 
So can you please change typings of url from string to URL.

Thanks

**Comment by rohit-010** [comment]
@suevalov  any update on this ??
