### ISSUE TITLE
getEnvironments is returning incorrect limit

### ISSUE THREAD

**Issue by mrkimbo** [contentful/contentful-management.js#369]
Hey all. 
Working on writing a Node script to check whether the current space has exhausted its environment limit and am seeing a different value for the `limit` returned via the API than in my UI.

My UI shows we have 31 possible environments available:
<img width="327" alt="conentful-environment-ui" src="https://user-images.githubusercontent.com/207823/84847640-e7461680-b094-11ea-9d24-ab3aece225d4.png">

The API returns a limit of 25:
<img width="434" alt="contentful-environments-api" src="https://user-images.githubusercontent.com/207823/84847768-2b391b80-b095-11ea-9f71-c3b12ff10c74.png">

Script:
```
// async
const client = createClient({ accessToken });
const space = await client.getSpace(spaceId);
const { total, limit } = await space.getEnvironments();
const message = `${limit - total} slots available (${total}/${limit})`;

if (total < limit) {
  console.log(chalk.green(`✅  ${message}`));
} else {
  console.log(chalk.red(`🚫️${message}`));
  process.exit(1);
}
```

Would be great to hear ideas on this - thanks :)

**Comment by suevalov** [comment]
Thanks for the question @mrkimbo!

`Limit` value doesn't represent an actual limit for your space. All our collection API endpoints have `total`, and `limit` in their response to paginate the results.

https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/collection-resources-and-pagination

So, 25 here is just a default page limit for a given endpoint. You can call `space.getEnvironments({ query: { limit: 100 }))` and it would return up to 100 items in one response.

Unfortunately, we don't have a public API to check space / environment limits, but there's a specific error code when you hit the limit and can't create new environments anymore.

Hope it helps!

**Comment by mrkimbo** [comment]
Hey - thanks for the quick response! 
I was aware of the `limit` prop in the `getEntries` request, but not in this one. Makes sense to keep it all aligned though. 

Looks like I’ll need to hard-code a `maxEnvironments` value for my scripts

**Comment by suevalov** [comment]
@mrkimbo We're looking into the possibility to make a public endpoint to read space/env limits. So, it might be added in the future.
