### ISSUE TITLE
Documentation is not compatible with Typescript

### ISSUE THREAD

**Issue by pixelass** [contentful/contentful-management.js#375]
## Expected Behavior

As a developer I expect the documentation to contain working snippets/guides.

## Actual Behavior

Several guides and snippets are incompatible with the typings.

## Possible Solution

One of the points listed could resolve this issue.

* Documentation should reflect the actual API
* Typescript should have a better documentation
* Typings should handle required and optional properties correctly

### Ugly workaround

The only way to use the API is to fool typescript via `as`.

```ts
space.createContentType({
    name: "Foo",
    fields: [],
} as Omit<ContentTypeProps, "sys">)
```

## Steps to Reproduce

The example below is just one of several cases. In general it seems like several methods are not typed correctly, making this library incompatible with typescript environments.

1. Go to https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types/content-type-collection/create-a-content-type/console/js
2. Go to: https://github.com/contentful/contentful-management.js/blob/c4a7e33eda7c2dea6fd3357420ec0be5652e9de8/lib/create-environment-api.ts#L272
3. The examples or typings are wrong (See: code comments and contentful.com/docs)

`displayType` and `description` are required in `ContentTypeProps` since only `sys` is omitted via:

```ts
Omit<ContentTypeProps, "sys">
```

As mentioned there are likely several of these issues.

## Context

The library is incompatible with typescript.

## Environment

-   **Language Version**: v12.15.0
-   **Package Manager Version**: yarn 1.22.4
-   **Browser Version**: 
-   **Operating System**: Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
-   **Package Version**:  5.27.1
-   **Which API are you using?**: Management

**Comment by suevalov** [comment]
Thanks for the details issue @pixelass 

I think our typings are not fully correct, sorry for that. Could you list all problematic typings?

**Comment by pixelass** [comment]
@suevalov I can list all of those I stumble upon. I can ist them in the first comment and extend the list over time or list them as separate comments (see below) and link them in the first comment to allow better readability of the issue. 

Here's another case I just noticed:

`ContentFields` is missing `validations`. 

```ts
export interface ContentFields {
  id: string,
  name: string,
  required: boolean,
  localized: boolean,
  type: string,

}

```

**Comment by suevalov** [comment]
@pixelass you can post as comments or update the description

We can quickly fix all issues with your help. Sorry for the inconvenience, we just recently converted this repository to Typescript and there are some inconsistencies.

**Comment by suevalov** [comment]
@pixelass could you please check out 🔝 PR?

**Comment by pixelass** [comment]
@suevalov you are right about `ContentFields`, I missed the `extends Item`,  I still had an error in that section, will report back tomorrow.

**Comment by pixelass** [comment]
@suevalov  Seems like the version I was using/testing (`^6.2.0-beta0`) does not extend `Item` anymore. 

**I forgot that I switched to see if the issues still existed in the v6-BETA.**

I switched back to `5.27.2` for now.

**Comment by suevalov** [comment]
@pixelass I see. I highly encourage you to use the latest stable which is `5.27.2`.

**Comment by pixelass** [comment]
@suevalov We're building a library to make using the contentful API (which IMHO is a very tedious process) easier, so we tested the BETA. 
Is there a roadmap for v6 or a planned release-date?

**Comment by suevalov** [comment]
@pixelass There is no planned release date and v6 most likely just remove deprecated methods
