### ISSUE TITLE
vanilla-js  entry won't update

### ISSUE THREAD

**Issue by bajeh1** [contentful/contentful-management.js#379]
Hi am new to Contentiful and am trying to update an item  but getting an Error:update is not a function.

here is my script tag: <script src="https://cdn.jsdelivr.net/npm/contentful@latest/dist/contentful.browser.min.js"></script>

    const client = contentful.createClient({
                accessToken: "BO8qgWsdeAa1pc-vcsf0ccg7Yx0srVOdgh",
                space: "0vyq810dddgdg",
              });

              client.getEntry("2tyzVfpA8QYKLCZwPVghj").then((entry) => {
                //   console.log(entry);
                tempItem.likes = likes + 1;
                entry.fields.likes = tempItem.likes;
                entry.update();
              });

**Comment by suevalov** [comment]
@bajeh1 This code snippet doesn't look right to me. You're using https://github.com/contentful/contentful.js which is Contentful Content Delivery API and you can't update entries with it. It's read-only API.

This repository and library for Contentful Content Management API: https://github.com/contentful/contentful-management.js

The following snippet should work:

```javascript
const contentful = require('contentful-management')

const client = contentful.createClient({
  accessToken: '<content_management_api_key>'
})

client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment-id>'))
.then((environment) => environment.getEntry('<entry-id>'))
.then((entry) => {
  entry.fields.likes = 10;
  entry.update()
})
```
