### ISSUE TITLE
createEnvironmentFromId resolves too soon

### ISSUE THREAD

**Issue by loremipson** [contentful/contentful-management.js#386]
## Expected Behavior

`await`ing environment creation with `createEnvironmentFromId()` should not resolve until the created environment is "complete".

## Actual Behavior

`createEnvironmentFromId()` resolves while the status is "queued" or "In Progress", and fails with a "The provided space does not exist, or you do not have access" error if a migration is attempted from `contentful-migration` at this stage.

## Steps to Reproduce
Assuming that you're using both `contentful-migration` and `contentful-management` along side each other.

We've needed a rather large space to reproduce this, I don't know exactly when this becomes an issue but this is a space with 1,822 records. This takes several seconds when a new environment is created to go from "In Progress" to "Complete" before it's ready to have migrations run on it.

**Comment by suevalov** [comment]
Hi @loremipson 

Environment creation with a lot of data takes some time and it's a known issue with `createEnvironmentWithId`. You can implement a simple polling logic. We have an example in your integration tests: https://github.com/contentful/contentful-management.js/blob/master/test/integration/integration-tests.js#L326-L333

**Comment by loremipson** [comment]
Awesome, similar solution works for me too. Thanks!
