### ISSUE TITLE
Type interface for the errors thrown by client API functions

### ISSUE THREAD

**Issue by davidhousedev** [contentful/contentful-management.js#392]
Thank you all for your work on this! The rich typing of this library is a huge help when creating rich deployment tooling.

In my project, there have been a few times where I want to catch an error thrown by a Contentful API call and respond differently based on the contents of the error. I've been looking for a type interface for the error that's built here: https://github.com/contentful/contentful-management.js/blob/master/lib/error-handler.ts but it looks like it's declared inline. Have you considered exporting an interface for it?

**Comment by suevalov** [comment]
Hi @davidhousedev! Thanks for the question and sorry for the long reply. We're considering adding a way to intercept error responses in the future versions of the CMA client.

**Comment by marcolink** [comment]
Closing this for now.
