### ISSUE TITLE
Missing documentation for "contentType.controls"

### ISSUE THREAD

**Issue by pixelass** [contentful/contentful-management.js#401]
## Expected Behavior

As a developer I expect the API to allow full configuration of the interface. The documentation should explain how this can be done.

## Actual Behavior

I don't see a way to update the `controls.settings` of an `Entry` (widgetId: `entryLinkEditor | entryCardEditor`)

<img width="872" alt="Page_—_Content_Model_—_evernest_com_—_Contentful" src="https://user-images.githubusercontent.com/1148334/87303561-aca89000-c513-11ea-8b24-0af6eca97048.png">

See: https://www.contentful.com/developers/docs/concepts/editor-interfaces/

> Widget ID | Setting name | Description
> -- | -- | --
> boolean | trueLabel | Shows this text next to the radio button that sets this value to true. Defaults to “Yes”.
> boolean | falseLabel | Shows this text next to the radio button that sets this value to false. Defaults to “No”.
> rating | stars | Number of stars to select from. Defaults to 5.
> datePicker | format | One of “dateonly”, “time”, “timeZ” (default). Specifies whether to show the clock and/or timezone inputs.
> datePicker | ampm | Specifies which type of clock to use. Must be one of the stringss “12” or “24” (default).

## Possible Solution

n/a
## Steps to Reproduce

follow documentation (see above)

## Context

We cannot create all parts of the editor interface via the API

## Environment

-   **Language Version**: v12.15.0
-   **Package Manager Version**: 6.13.4
-   **Operating System**: 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
-   **Package Version**: v5.27.3
-   **Which API are you using?**: Management

**Comment by pixelass** [comment]
@suevalov This issue was not about the typings but rather missing  options in the API and is therefore not resolved.

> As a developer I expect the API to allow full configuration of the interface.

Setting "Show Create new Entries"  &  "Show Link existing Entries" is neither defined nor described anywhere.  
I'm not even sure if it's even possible to set these options via the API.

**Comment by cxcorp** [comment]
related, and also not resolved by the update: #407
