### ISSUE TITLE
Space.getContentType() deprecated?

### ISSUE THREAD

**Issue by pixelass** [contentful/contentful-management.js#403]
## Expected Behavior

As a developer I expect links to pages in log messages to be available

## Actual Behavior

Does not exist: https://contentful.github.io/contentful-management.js/contentful-management/latest/ContentfulEnvironmentAPI.html#.getContentType 

## Possible Solution

n/a
## Steps to Reproduce

1. use the contentful management api with `Space.getContentType()`
2. see logs:
```
Deprecated: Space.getContentType() will be removed in future major versions.

Please migrate your code to use Environment.getContentType():
https://contentful.github.io/contentful-management.js/contentful-management/latest/ContentfulEnvironmentAPI.html#.getContentType
```
3. follow the link

## Context

I am unsure if `Space.getContentType()` is deprecated and I can't find the documentation for `Environment.getContentType()`.

## Environment

-   **Language Version**: v12.15.0
-   **Package Manager Version**: 6.13.4
-   **Operating System**: 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
-   **Package Version**: v6.0.0
-   **Which API are you using?**: Management

**Comment by suevalov** [comment]
Thanks for the question @pixelass 

Yes, `space.getContentType` is deprecated (along with some other space functions) and will be removed in the upcoming major release.

All deprecated methods are available in the `environment` namespace: https://contentful.github.io/contentful-management.js/contentful-management/6.0.0/globals.html#createenvironmentapi

**Comment by pixelass** [comment]
@suevalov You might want to update the log-message to point to the correct docs.
