### ISSUE TITLE
Type definitions for environment aliases are incorrect

### ISSUE THREAD

**Issue by seleb** [contentful/contentful-management.js#406]
Hey there! Updated this dependency on a project recently, and there appear to be some breaking changes in the type definitions which don't line up with the implementation of the environment alias:

 - all of the properties defined on the `{ environment }` prop actually exist under `{ environment: { sys } }`
 - the `update` function has a `data` argument which implies a delta can be passed in, but updating still requires modifying the alias properties and then calling `update`; the argument appears to do nothing

**Comment by suevalov** [comment]
Thanks for reporting the issue @seleb. The fix is on the way and should be released shortly.
