### ISSUE TITLE
Question: Creating an entry to link while creating another entry

### ISSUE THREAD

**Issue by DevanB** [contentful/contentful-management.js#412]
Hey there! 👋 

I'm working through a _large_ migration from a CMS into Contentful (> 20,000 objects across ~30 content models). I believe I know the answer to my question, and figured it wouldn't hurt to ask anyways. 

I'm processing through multiple CSVs, many of which have relationships to other models and various levels of links within the same model. I'm using the `createEntryWithId` method to create my entries and specify my unique ID's so I can use them as links. The issue comes when I'm creating a link to an object that hasn't been created yet. As I see it, I have two options here:

1. On my first pass, I create ALL objects, then make a second loop through my data to publish all entries. It seems with this manner that you can create a link to a piece of content that doesn't exist, but you can't publish the entry with the bad link. By making this second pass, I can hopefully ensure all objects are created, links are established, then I can publish.

or 

2. I can create an entry and link, and create the linking entry then. The catch to this is there doesn't seem to be an API for this.

So the questions:

1. Am I indeed correct there isn't any API for creating an entry that is linked when creating an entry?

2. Is there any sort of "publish all" for a content model that I can use programmatically? This would save me from making a second pass at all of my data, if I needed to take this route.

Any guidance, thoughts, and/or suggestions are most welcome. It seems Contentful doesn't have the most robust tools to help migrate data in, so I'm navigating uncharted waters. 

Thanks! 😄

**Comment by suevalov** [comment]
Hi @DevanB, thanks for the questions!

1. Unfortunately there's no API for creating an entry that is linked. I'd recommend to create a content type with link field and relax the validation to allow publishing an entry without a link value, so you can create all entries in one go. As the second step of your script you'd link entries between each other.

2. Unfortunately there's no public API to "publish all" at the moment, but we're working on it and may show up in the client in the future.
