### ISSUE TITLE
Locale missing in Typings

### ISSUE THREAD

**Issue by shahzainb** [contentful/contentful-management.js#417]
Hi,

I was just working on some Typescript code for my project and noticed that locale is missing in `EntrySys` at https://github.com/contentful/contentful-management.js/blob/master/lib/entities/entry.ts#L28. It's also not available in the `experimental` branch (understandbly as it's still WIP).

Thanks!

**Comment by suevalov** [comment]
Hi @shahzainb!

Contentful Management API returns entries for all locales in one response and there's no `locale` in `sys` object.
Maybe are you mixing it with Contentful Delivery API https://github.com/contentful/contentful.js

**Comment by shahzainb** [comment]
Hi @suevalov, I'm going to close this as I'm not longer with that project working on the Contentful stuff that I was working on, and don't remember the context of this.

Thanks.
