### ISSUE TITLE
Upload an image from PC 

### ISSUE THREAD

**Issue by maverickosama** [contentful/contentful-management.js#43]
Hi is there any way to upload an image via PC. I need to upload it. Please help.

**Comment by trodrigues** [comment]
Hi there,

not directly. Our media Asset system on the server always needs to get an asset from an existing URL.

**Comment by surju87** [comment]
Hi,

does contentful have any plan to provide feature to upload file from local/non-url location.

**Comment by Khaledgarbaya** [comment]
Hi @surju87 ,
Unfortunately it still the same for now
