### ISSUE TITLE
Bug: Unable to delete app-installation entity using SDK

### ISSUE THREAD

**Issue by AndrewOstrovsky** [contentful/contentful-management.js#440]
Hello,

According to docs:

```
client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment_id>'))
.then((environment) => environment.getAppInstallation('<app_definition_id>'))
.then((appInstallation) => appInstallation.delete())
.then(() => console.log(`App installation deleted.`))
.catch(console.error)
```

should delete app installation entity however it always throws an error since appInstallation doesn't have an id

Error:
`{
  "status": 404,
  "statusText": "Not Found",
  "message": "The resource could not be found.",
  "details": "AppInstallation does not exist.",
  "request": {
    "url": "app_installations/undefined", ...
  },
  ...
}
`

SDK version: 5.27.3

I suspect there is an issue with `createDeleteEntity` -> https://github.com/contentful/contentful-management.js/blob/master/lib/entities/app-installation.ts#L78

This function expects that ID is defined on entity level (within "sys") however as far as i understood AppInstallation doesn't have it's own ID instead of that it's using **app_definition_id** to update/delete entity see https://github.com/contentful/contentful-management.js/blob/master/lib/entities/app-installation.ts#L74

Thanks in advance!

**Comment by FLoppix** [comment]
Hey @AndrewOstrovsky,
thanks for pointing this out! This should be fixed in the latest version https://github.com/contentful/contentful-management.js/releases/tag/v6.1.2
