### ISSUE TITLE
How to get the entry status

### ISSUE THREAD

**Issue by nikolaiwu** [contentful/contentful-management.js#46]
Hi, I'm using contentful-management in combination with a graph plugin to visualize the entries, and relations between them. However, I can't find a way to determine the entry status. Can't find it in documentation, either. Can you tell me how to get the status of an entry, by the object returned, or redirect me to some documentation. Thanks!

**Comment by trodrigues** [comment]
This feature is now available on the newest version of the SDK.

**Comment by nikolaiwu** [comment]
Can you please, give me a little more info on that SDK, where can I find it, documentation, etc. I've googled it, but didn't found much. Thank you!

**Comment by Khaledgarbaya** [comment]
Hi @nikolaiwu you can find all the info you need about the new SDK [here](https://www.contentful.com/blog/2016/06/02/js-cma-sdk-v1/), the blog post contains links to the documentation and migration guide.
for getting the entry status : the entry now has properties like `isPublished`,`isUpdated`, `isDraft` that you can use to determine the status .

**Comment by nikolaiwu** [comment]
@Khaledgarbaya Thank you very much, that's exactly what I was looking for! I'll check it out!
