### ISSUE TITLE
Issues with type definitions for Space API

### ISSUE THREAD

**Issue by trodrigues** [contentful/contentful-management.js#50]
https://contentful.github.io/contentful-management.js/contentful-management/1.0.4/ContentfulSpaceAPI.html

- It shouldn't be ClientAPI, it should be ContentfulSpaceAPI
- List of all methods available on the type is incomplete (no creation methods, etc)

**Comment by trodrigues** [comment]
Btw, @Khaledgarbaya it's not a big deal for this case, but for these situations where you're actually fixing issues in the docs and you want to force a redeployment (because of semantic-release) you can use `fix(docs):` in the commit message, as using a `docs():` won't increase the version number and trigger a redeployment.

**Comment by Khaledgarbaya** [comment]
Yeah I just figured out that, it should fine now
