### ISSUE TITLE
Contentful Media Asset - Upload images using external URL

### ISSUE THREAD

**Issue by sopmishra** [contentful/contentful-management.js#52]
We are trying to upload an image using an external URL into Contentful Media Assets.
A new record is being created but the File is showing as "Processing" even after considerable time.
Manually hitting the image URL, downloading the image and then uploading to Contentful is working fine but programmatic approach is not working. Please find below a sample JSON request structure for reference

Headers - Content-Type:application/vnd.contentful.management.v1+json
Body -  {
"fields": {
	"title":{
		"en-US": "Bacon Pancakes"
		},
		"file":{
			"en-US":{
			"contentType":"image/jpeg",
			"fileName":"example.jpeg",
			"upload":"https://example.com/example.jpg"
			}
		}
	}
}

![asset_img](https://cloud.githubusercontent.com/assets/19264202/16220426/7210aeb4-37aa-11e6-9831-6cedd4d41f8e.jpg)

**Comment by rmohanreddy** [comment]
Hi Sopan

We need to make a call to process API too then the image will be processed/ uploaded
Put https://api.contentful.com/spaces/<space_id>/assets/<asset_id>/files/<locale>/process

Thanks
Ramesh

**Comment by rmohanreddy** [comment]
Hey

I used angular brackets earlier, for space id and asset id which appeared

Here is the process URL 
Put https://api.contentful.com/spaces/space_id/assets/asset_id/files/locale/process

Thanks
Ramesh

**Comment by trodrigues** [comment]
This can now be done with the `asset.processForLocale('locale-code')` call or `asset.processForAllLocales()`. Please check the documentation for these [here](https://contentful.github.io/contentful-management.js/contentful-management/1.0.6/Asset.html#.processForAllLocales) and the documentation for createAsset [here](https://contentful.github.io/contentful-management.js/contentful-management/1.0.6/ContentfulSpaceAPI.html#.createAsset) which references the whole process
