### ISSUE TITLE
Blob or Base64 image upload?

### ISSUE THREAD

**Issue by sntiagomoreno** [contentful/contentful-management.js#538]
Is it possible in any way to upload a blob url or a base64 image? Can't find anything related and when trying to pass a blob or base 64 I'm always getting the following error

```
"errors": [
      {
        "name": "regexp",
        "details": "Does not match /^https?://[^ \"]+$/",
        "value": ...
```

**Comment by suevalov** [comment]
Hi @sntiagomoreno! We don't support uploading base64 images, but we do support uploading of ArrayBuffer.

You can convert base64 to ArrayBuffer and upload file using `createAssetFromFiles` function
