### ISSUE TITLE
Broken link in the README

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful-management.js#54]
In the 'You can start by looking at the top level contentfulManagement namespace.'
'contentfulManagement' part is a link pointing to  https://github.com/contentful/contentful-management.js/blob/master/contentfulManagement.html which does not exist in the repo anymore

**Comment by qbunt** [comment]
@Khaledgarbaya are you still seeing this issue?

**Comment by Khaledgarbaya** [comment]
Hi @qbunt, 
The thing is that this link is intended to be working only when in the github page.
I think I'll close this issue for now and get back to it one day
