### ISSUE TITLE
Example of how to create a link

### ISSUE THREAD

**Issue by ivanoats** [contentful/contentful-management.js#57]
Do you have a code sample available of how to create a new entry, and link it to an existing entry of a different content type?

**Comment by Khaledgarbaya** [comment]
Hi @ivanoats ,

this could be an example : 

```javascript
//....
space.createContentType({name: 'Blog', fields: [{
      "name": "Author",
      "id": "author",
      "type": "Link",
      "linkType": "Entry"
    }]}).then((contentType) => {
      // contentType is created but it is still in draft you will need to publish it
      console.log(contentType.isDraft())
      contentType.publish().then((contentType) => {
         console.log('contentType is published')
     })
})
```

Tip : 
You can always play around with creating content models and check its preview JSON that's usually the same payload that you'll need to send to create it via the API except some fields of course like id etc

**Comment by ivanoats** [comment]
Thanks. Would that code work with localizations though? My current code looks like below, which is different:

```javascript
const result = await space.createEntry('legacyPost', {
      sys: {
        createdAt: post.created_at,
        updatedAt: post.updated_at,
      },
      fields: {
        title: { 'en-US': post.title },
        body: { 'en-US': post.body },
        slug: { 'en-US': post.slug },
        authorName: { 'en-US': post.author_name },
        intro: { 'en-US': post.intro },
        description: { 'en-US': post.description },
        scheduledPubTime: { 'en-US': post.scheduled_time },
        imageCredit: { 'en-US': post.image_credit },
        legacyFeaturedImageUrl: {
          'en-US': `${assetHost}/blogs/${post.id}/featured_images/${post.featured_image_file_name}`,
        },
```

**Comment by Khaledgarbaya** [comment]
Hi @ivanoats ,
Yes you just need to add `localized: true` like so 

```javascript
//....
space.createContentType({name: 'Blog', fields: [{
      "name": "Author",
      "id": "author",
      "type": "Link",
      "localized": true,
      "required": false,
      "disabled": false,
      "omitted": false
      "linkType": "Entry"
    }]}).then((contentType) => {
      // contentType is created but it is still in draft you will need to publish it
      console.log(contentType.isDraft())
      contentType.publish().then((contentType) => {
         console.log('contentType is published')
     })
})

```
Note you can also set field as required or omit it so it wont show up in the request also disable it in the contentful Editor

**Comment by ivanoats** [comment]
I'm not asking about creating a content type, I'm asking about creating an entry linked to another entry.

**Comment by Khaledgarbaya** [comment]
Hi @ivanoats ,
To include an already created Entry as a link your fields should like something like
```js
fields: {
        legacyPost: {en-US: {sys: {type: "Link", linkType: "Entry", id: "entry_id"}}}
       ....
     }
```

Where `entry_id` is the entry that you want to link

**Comment by ivanoats** [comment]
Thank you, that's exactly what I was looking for.

**Comment by ivanoats** [comment]
Could you also please provide an example of how to link multiple entries (an arary) while updating an entry?

For example, here is a part of the content model:
```javascript
{
      "id": "createdEntries",
      "name": "Created Entries",
      "type": "Array",
      "localized": false,
      "required": false,
      "validations": [],
      "disabled": false,
      "omitted": false,
      "items": {
        "type": "Link",
        "validations": [
          {
            "linkContentType": [
              "2wKn6yEnZewu2SCCkus4as"
            ]
          }
        ],
        "linkType": "Entry"
      }
    },
```

and I assume I have to merge the createdEntries property into the existing fields of an entry, something like this?

```javascript
    const fieldsToMerge = {
      createdEntries: {
        'en-US': {
          sys: {
            type: 'Link',
            linkType: 'Array',
// what goes here?
          },
        },
      },
    }
```

**Comment by Khaledgarbaya** [comment]
hi @ivanoats let say as an example you have a blog post with multiple authors
so in the post payload you will have something like : 

for content model creation

```json
fields: [ {
      "name": "Authors",
      "id": "authors",
      "type": "Array",
      "items": {
        "type": "Link",
        "linkType": "Entry",
        "validations": [
          {
            "linkContentType": [
              "blog"
            ]
          }
        ]
      },
      "validations": []
    },
  ....]
```
**Note the extra items fields there which defines the type of the type of the linked entry that could be referenced multiple time**

**Comment by ivanoats** [comment]
Thanks again, but also, I am asking about Posting new arrays of links, not content model creation.

**Comment by Khaledgarbaya** [comment]
Hi @ivanoats 
The differences in most of the cases between a single element and multiple elements are type which is `Array` and if it is an array you add the items fields which is  an array of the elements that will be contained
I hope that's answer your question and feel free to post questions anytime I will try my best to answer them 

Best,
Khaled

**Comment by stevenpetryk** [comment]
Hello from the future,

Imagine we have an entry with a many-to-many field, let's call it Author (and author has many Posts).

How do we create an Author (entry, NOT content type) AND join multiple posts to it? In other words,

* I know how to make an entry.
* I know how to make an author and a post.
* **How do I make an author and then link posts to it?**

**Comment by stevenpetryk** [comment]
To be extra clear, I know how to make a content type that accepts multiple posts. How do I link multiple, already-created Post entries to a single Author entry?

**Comment by Khaledgarbaya** [comment]
Hey @stevenpetryk ,

your payload should look like this:

```js
"fields" : {
...
  "posts": {
      "en-US": [
        {
          "sys": {
            "type": "Link",
            "linkType": "Entry",
            "id": "<post-id>"
          }
        },
        {
          "sys": {
            "type": "Link",
            "linkType": "Entry",
            "id": "<another-post-id>"
          }
        }
      ]
    }
}

```

**Comment by Abhishekpuvvada25** [comment]
hi, if I have 100 objects in an array, would i have to now manually create 100 objects with unique ids?
