### ISSUE TITLE
Incorrect Typescript definitions

### ISSUE THREAD

**Issue by nekosaur** [contentful/contentful-management.js#576]
1. `createSpaceMembership` on `Space` incorrectly requires a `name` property when it should be `email`
```js
// CURRENT
space.createSpaceMembership({
  admin: true,
  name: '???',
  roles: [],
});

// CORRECT
space.createSpaceMembership({
  admin: true,
  email: 'hello@world.com',
  roles: [],
});
```
Additionally, `roles` is marked as required when it is not if using REST API.

2. `createLocale` on `Environment` incorrectly requires `internal_code`
```js
env.createLocale({
  code: locale.code,
  name: locale.name,
  fallbackCode: null,
  internal_code: '???' // This is not required through REST API, and things work correctly if ignoring the TS error
})
```

**Comment by suevalov** [comment]
Thanks for reporting @nekosaur, we'll release a fix shortly
