### ISSUE TITLE
X-Contentful-Content-Type required for updating entry

### ISSUE THREAD

**Issue by rosinghal** [contentful/contentful-management.js#58]
Can you please change createEntryWithId function with below as 'X-Contentful-Version' is required while updating any entry?
`
	function createEntryWithId(contentTypeId, id, data, version) {
	    return http.put('entries/' + id, data, {
	      headers: {
	        'X-Contentful-Content-Type': contentTypeId,
	        'X-Contentful-Version': version
	      }
	    }).then(function (response) {
	      return wrapEntry(http, response.data);
	    }, _errorHandler2.default);
	  }
`

**Comment by Khaledgarbaya** [comment]
Hi @rosinghal I will try to investigate this, but can you explain more what are you trying to do and what went wrong

**Comment by Khaledgarbaya** [comment]
Hi @rosinghal, the purpose of this function is to create an entry with a specific id and creation does not require the version. version is only required when updating and entry

**Comment by rosinghal** [comment]
I am just trying to update the entry using sysid. As mentioned in documents I will need to pass X-Contentful-Content-Type header with it. If you can maybe create a new function.

**Comment by Khaledgarbaya** [comment]
but that is creating an entry not updating it.
Updating an entry could be done like so 

```js
var contentful = require('contentful-management')
var client = contentful.createClient({
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: 'YOUR_ACCESS_TOKEN'
})

// This API call will request a space with the specified ID
client.getSpace('spaceId')
.then((space) => {
  // let's get a content type
  space.getEntry('entryID')
  .then((entry) => {
    // and now let's update its name
    entry.fields. name = 'New Product'
    entry.update()
    .then((updatedEntry) => {
      console.log('Update was successful')
    })
  })
})
```

**Comment by rosinghal** [comment]
Got it. Thanks.
