### ISSUE TITLE
Insecure should not be true by default

### ISSUE THREAD

**Issue by kimmobrunfeldt** [contentful/contentful-management.js#60]
In createClient, `insecure` option is true by default at least by the documentation.

I think by default the client should use safer https instead of http. Is there a reason why you have chosen to default to insecure http protocol?

**Comment by Khaledgarbaya** [comment]
Hi @kimmobrunfeldt ,

Thank you for pointing this up, it is just a typo in the documentation, the default as you can see from the code is false actually.

I will change it right away, thanks for pointing that up

Best,
Khaled

**Comment by scott-joe** [comment]
Is this still an issue in the [documentation](https://contentful.github.io/contentful.js/contentful/latest/contentful.html#.createClient)? It still lists the default as `true`. I looked at the [linked source](https://contentful.github.io/contentful.js/contentful/latest/contentful.js.html) and it doesn't appear to use the option, but it persists.
