### ISSUE TITLE
docs for Space.getLocales()?

### ISSUE THREAD

**Issue by bnchdrff** [contentful/contentful-management.js#62]
in order to set an entry's field values, i want to get a space's default locale.

[the documentation](https://contentful.github.io/contentful-management.js/contentful-management/1.1.14/Space.html#.Space) indicates that a Space has a property `locales` -- but this isn't the case from what i can tell. the code shows a method `getLocales` but this isn't in the docs.

**Comment by Khaledgarbaya** [comment]
Hi There the locale object has a property called `default` if it is true that's the default locale.
So to get that you can do.

```javascript
var contentful = require('contentful-management')
let client = contentful.createClient({
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: 'MANAGEMENT_TOKEN'
})
client.getSpace('SPACE_ID').then( (space)=> {
     space.getLocales().then((localeCollection)=>{
         let defaultLocale = localeCollection.items.filter((locale)=>{return locale.default})
     })
})
```

I hope this help

**Comment by bnchdrff** [comment]
Nice, i got that part; my concern is that the docs at https://contentful.github.io/contentful-management.js/contentful-management/1.1.14/Space.html#.Space don't seem to be correct.

**Comment by Khaledgarbaya** [comment]
Ah yeah you are right the space object does not contain `locales` property I will fix that right away, thank you for pointing that up

**Comment by bnchdrff** [comment]
is getLocales covered in the docs somewhere? i couldn't find it

**Comment by Khaledgarbaya** [comment]
you can find it here https://contentful.github.io/contentful-management.js/contentful-management/1.1.14/ContentfulSpaceAPI.html#.getLocales

**Comment by bnchdrff** [comment]
ah, i was looking at the wrong page. thank you!
