### ISSUE TITLE
bug within processForLocale (processingCheckWait, processingCheckRetries)

### ISSUE THREAD

**Issue by floridemai** [contentful/contentful-management.js#64]
When `asset.processForLocale` is used one can pass two additional parameters in order to establish how long to wait for asset processing (`processingCheckWait`, `processingCheckRetries`).
The bug is that after the first setTimeout both parameters are reset to their default values (5 & 500) because they are not passed further down the setTimeout chain.

**Comment by Khaledgarbaya** [comment]
Hi @floridemai ,
Oh Yeah good catch I will fix this asap
Best,
Khaled
