### ISSUE TITLE
How to create a contentType with this lib ?

### ISSUE THREAD

**Issue by moimael** [contentful/contentful-management.js#66]
Hi,

How can I create a contentType with this lib ?

I can do it by calling the api directly but then it doesn't integrate nicely with this lib.

Is this supported or is it a new feature ?

Thanks !

**Comment by Khaledgarbaya** [comment]
Hi @moimael ,
You can create a new contentType by caling the `client.createContentType(payload)`

e.g:

```js
const contentful = require('contentful-management')
const client  = contentful.createClient()
// you can also Create a space by calling createSpace
client.getSpace('SPACE_ID').then( (space) => {
      // you can add more stuff like fields etc in the payload
      space.createContentType({name:'mycontentType'}) 
}) 
```

you can also check the [SDK reference](https://contentful.github.io/contentful-management.js) for more infos

**Comment by moimael** [comment]
Thanks a lot, I was looking in the ContentType part of the doc, didn't see it was in Space.

**Comment by Khaledgarbaya** [comment]
@moimael , The space owns everything, once created the conntentType, you will get a contentType instance that you can manipulate, update, delete etc ...
