### ISSUE TITLE
add method to omit and delete fields at once

### ISSUE THREAD

**Issue by moimael** [contentful/contentful-management.js#67]
Hi,

When I try to edit or delete an existing field in a contentType, I get an error.

For deleting: `You need to omit a field before deleting it`
For updating: `Previously published fields are invalid`

For deleting I understand I can first omit a field and then delete it, but shouldn't that be taken care of in this lib ?

Do I also need to omit the field first to be able to edit an existing field ?

Thanks !

**Comment by Khaledgarbaya** [comment]
Hi @moimael ,
When trying to delete a field you need to set `omitted` to `true` then call update, than set `deleted` to `false` and update and publish.

For more info check the docs [here](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types/content-type)  in the `Deleting Fields` section

Best,
Khaled

**Comment by moimael** [comment]
Hi, @Khaledgarbaya,

Thanks for your answer !

While I do get why there is a 2 step process to delete fields, it would be great to provide an option in the api to delete directly. In my use case I always want to delete the field directly.

How about updating a field ? Like changing the type ? Is that a 3 step process ? Should I delete first and then replace the field with the updated version, or can I omit the field first and then send the updated field ?

**Comment by Khaledgarbaya** [comment]
Hi @moimael ,
Make sense to get maybe omitandDelete function in the SDK.
For changing the field I think you can change the editor interface of the contentType.
the SDK already supports that : 

```js
var editroInterface = await contentType.getEditorInface()
editorInterface.controls[0].widgetId = 'MultiLine' //
await editorInterface.update()
```

**Comment by Khaledgarbaya** [comment]
and here is the list of possible widgetIds : 
```
singleLine
urlEditor 
numberEditor
multipleLine
markdown
dropdown
radio
boolean
rating
datePicker
locationEditor
objectEditor
listInput
checkbox
tagEditor
fileEditor
entryLinkEditor
assetLinkEditor
entryLinksEditor
entryCardEditor
entryCardsEditor
assetLinksEditor
assetGalleryEditor
slugEditor
ooyalaEditor
ooyalaMultiAssetEditor
kalturaEditor
kalturaMultiVideoEditor
```

**Comment by moimael** [comment]
Thanks ! 

omitAndDelete function would be awesome !

By changing the field type, I meant changing it from Symbol to Text for example or from Symbol to Date.
With the update function in the SDK this throws an error.

**Comment by Khaledgarbaya** [comment]
Yeah in that case you need to delete and recreate

**Comment by moimael** [comment]
Ok then it makes event more sense to have a omitAndDelete function, otherwise it is a 4 step process to update a field type. Omit, delete, create and publish.

**Comment by Khaledgarbaya** [comment]
@moimael I will plan this, but contributions are welcome also
