### ISSUE TITLE
Entity PATCH support?

### ISSUE THREAD

**Issue by randonia** [contentful/contentful-management.js#681]
I was wondering if there were plans to implement `PATCH` support for entities? The [official documentation](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entry) has the method listed, and the HTTPs endpoint works, but there are no code samples (it seems the [documentation entry](https://www.contentful.com/developers/_resources/snippets/cma/entries/entry/patch-an-entry.json) does not exist) and the method doesn't seem to exist in either the Plain or Default libraries:

* https://github.com/contentful/contentful-management.js/blob/master/lib/plain/endpoints/entry.ts
* https://github.com/contentful/contentful-management.js/blob/master/lib/entities/entry.ts

Are there plans to integrate this endpoint?

**Comment by cribbles** [comment]
Hi @randonia, thanks for filing this.

PATCH support in this library is indeed on our roadmap and should become available in the near term. I'll keep you posted with any updates. In the meantime we've updated the documentary entry to reflect cURL usage and will add a code sample illustrating usage with the JS CDK when that becomes available.

**Comment by luizfonseca** [comment]
P.S.: The patch endpoint is already part of the library: https://github.com/contentful/contentful-management.js/blob/c1d4313c30c6e0e9abbc765d25f31d16f87f1747/lib/create-entry-api.ts#L93

You can use 

```
const entry = await environment.getEntry('<entryId>') 
// and then

entry.patch([
 // array of patch operations 
])
```

or through the `plainClient` with `plainClient.entry.patch(...)`

Let me know if we can close this issue 👍🏽

**Comment by randonia** [comment]
Thanks for the update! I think this can be closed now :)
