### ISSUE TITLE
Documentation regarding the interaction between this lib and contentful.js

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful-management.js#70]
The new contentful.js doesn't rely on making calls to methods on a space object.  It is not clear for the documentation if this library still uses that convention.
Are there updated docs that show the interaction between these two libraries?

**Comment by Khaledgarbaya** [comment]
Hi @dmorrow,
There is no interaction between contentful.js and contentful-management.js. They are completly different, Contentful.js is read only content delivery SDK, so you only will be able to pull content with. contentful-management.js is read and write management SDK, so you can edit your entries and create new ones etc ... they both have their own Documentations and they are completely seperate.

I hope that clarify things for you 

Best,
Khaled

**Comment by dmorrow** [comment]
Thank you.  I had assumed that the read portion of the manager was handled by the contentful.js lib.
