### ISSUE TITLE
Query Assets not returning assets with / in title

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful-management.js#71]
Node Version: v4.4.5
Npm Version: 3.9.2
Platform: OSX
Package Version:contentful-management@1.2.1
When querying assets using contentful-management@1.2.1 I do not receive Assets that have a / character in their name.

`space.getAssets({ 'query':'-preview', 'limit': 1000 })`

I am able to verify that Assets that do not have a / character in their title appear. If I remove the query param from the request, I am able to receive the assets with the / in the title.

Strangely, the array of Asset objects that I receive matches the count of Assets I can see in the web interface. I currently have 300+ assets that match '-preview', so I have not been able to confirm how this is possible. I have de-duped the returned array, and there doesn't seem to be duplicates either.

This was originally asked in **contentful.js**.  Just moving it over.

**Comment by Khaledgarbaya** [comment]
Hi @dmorrow ,
I am assuming that you are querying  all assets that their titles match '-preview', the syntax you are using is for `full text search` for `Symbols` or `Text` fields. What you wanna use is the fields full text search syntax which is like so :
`space.getAssets({ 'fields.title[match]':'-preview', 'limit': 1000 })`

For more infos checkout the documentation [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/full-text-search-on-a-field/query-entries?console=1)
I hope that solves your issue.

Best,
Khaled

**Comment by dmorrow** [comment]
@Khaledgarbaya Using the fields.title[match] syntax does not change the results.

**Comment by Khaledgarbaya** [comment]
Hi @dmorrow do you still have this issue ?

**Comment by dmorrow** [comment]
@Khaledgarbaya yes.  We have a ticket in with support, but I don't believe any progress has been made.  If you can inquire from your end that would be helpful.
I can still see this behavior in the Contentful Web GUI as well.

**Comment by Khaledgarbaya** [comment]
@dmorrow 

This code was working for me fine

```js
var contentful = require('contentful-management')
var client = contentful.createClient({
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: 'ACCESS_TOKEN'
})
// This API call will request a space with the specified ID
var space = await client.getSpace('SPACE_ID')

await space.getAssets({'fields.title[match]': 'something'})
```

and this is is the output 
![screen shot 2017-01-10 at 15 14 35](https://cloud.githubusercontent.com/assets/1156093/21809337/8bf3a7f4-d747-11e6-87db-bca36ef6cc98.png)

**Comment by dmorrow** [comment]
@Khaledgarbaya Yes, in general the `[match]` or `query` code works correctly.  However, the issue is when there is a `/` in the field you are querying and the query or match comes **AFTER** the slash.

We have many assets with the title pattern '....SS15/16-preview'.  We try to `[match]` on `-preview`, however it does not select these titles.  However, it does select files with the pattern '...AW15-preview' flawlessly.

**Comment by Khaledgarbaya** [comment]
@dmorrow ah yeah you are right I was able to to replicate the issue, I will check with the backend engineers

**Comment by Khaledgarbaya** [comment]
@dmorrow I closing this issue, since it is a backend issue
