### ISSUE TITLE
Typings issue in wrap.d.ts

### ISSUE THREAD

**Issue by jugglingthebits** [contentful/contentful-management.js#775]
Updating our dependency on `contentful-management` from 7.11.0 to 7.12.0 broke compilation for us. TypeScript outputs multiple errors:

![grafik](https://user-images.githubusercontent.com/3235163/112633387-97715880-8e39-11eb-98d2-bd9a44c1d5fa.png)

Updating to 7.13.0 fails with the same errors.

**Comment by andipaetzold** [comment]
Hey @jugglingthebits,

I am sorry for your issues!
Version 7.13 was a pretty big internal refactor and it seems like the new release is not error-free yet.

Which version of TypeScript are you currently using?

**Comment by jugglingthebits** [comment]
Were using TypeScript 4.2.3

**Comment by jugglingthebits** [comment]
> Version 7.13 was a pretty big internal refactor and it seems like the new release is not error-free yet.

7.12.0 shows the same issue for us

**Comment by andipaetzold** [comment]
> > Version 7.13 was a pretty big internal refactor and it seems like the new release is not error-free yet.
> 
> 7.12.0 shows the same issue for us

The refactoring was done in 7.12 and 7.13. 7.12 is only a pre-release.

I'll investigate the issue and will come back to you as soon as I have an update/fix.

**Comment by andipaetzold** [comment]
I released a new version yesterday ([7.13.1](https://github.com/contentful/contentful-management.js/releases/tag/v7.13.1)) that should resolve your type issue.
Could you please update to that version and check whether it now compiles successfully?

**Comment by jugglingthebits** [comment]
@andipaetzold version 7.13.1 works nicely now. Thank you for resolving this issue.
