### ISSUE TITLE
Content Type needs to be saved explicitly even after publishing 

### ISSUE THREAD

**Issue by swatikurra** [contentful/contentful-management.js#78]
Hi,
I was creating a content type using **createContentTypeWithId** method and after publishing, it shows on the destination as well. But when i move entry of same content type, its name doesn't reflect, instead of name it shows untitled. (Although i can see the name after opening it).
After saving the content type explicitly, name reflects back in the entry dashboard.

Can you please suggest, how can i save content type explicitly or what am i missing ?

**Comment by Khaledgarbaya** [comment]
Hi @swatikurra ,
Did you pass in the name property when creating your contentType.
Can you share with me a snippet of code if possible?

Best,
Khaled

**Comment by swatikurra** [comment]
Hi Khaled, 
Yes, i did pass the name property 
Here is the screenshot. 
![capture](https://cloud.githubusercontent.com/assets/20393958/22973099/a748e27c-f3a2-11e6-90b4-04cd2cf4df30.PNG)
Although after opening , it shows the name. 
![image](https://cloud.githubusercontent.com/assets/20393958/22973136/cdf2feb2-f3a2-11e6-90ca-45a1d4f8b7e5.png)



`data = contenType.fields; //get contenttype field object from source
                                        fieldData.fields = data;
                                        fieldData.name = contenType.name;  //content name from source
space.createContentTypeWithId(contenTypeID, fieldData)
                                             .then((ct) => {
                                                 ct.publish()
                                                 .then((pct) => {
                                                    //print published version
                                                 })`

**Comment by Khaledgarbaya** [comment]
Hi @swatikurra,
I missed one more step, you need to add the `displayField` property and its value is the ID of the field that you want to use a display.

Best,
Khaled

**Comment by swatikurra** [comment]
Hi Khaled, 

Thank you so much. It worked now :)
One more thing we are facing if you can help in that - 
While migrating  large chunk of assets and entries, we are getting 429 error. Although it is written in the API that the rate limit handling has been implemented in it. 

Can you suggest what needs to done to handle bulk migration ?

Thanks again for quick response!

**Comment by Khaledgarbaya** [comment]
Hi @swatikurra,

If you have a lot of assets you would be probably hitting the per hour rate limit so maybe try to lower the number of request per second to compensate for that. using `rateLimit` and `rateLimitPeriod` when creating the client.
ps: make sure to wait for the hour to end before trying that.
Best,
Khaled

**Comment by swatikurra** [comment]
Hi Khaled, 

I am sure we are not hitting the hourly rate limit. Even sometimes, while moving just 10-15 assets(which would take hardly a minute or 2), 429 error comes up. 
It would be really helpful if you could explain how API is handling this thing internally, As somehow this is not working for us ?
I have also verified that the max retries option has been set to 5 (default) in API. 
Please suggest what can we do to combat this error ?

Thanks, 
Swati

**Comment by Khaledgarbaya** [comment]
Hi @swatikurra,

Please note that rate limit is per organization and not per user, so you maybe doing something and someone else also creating content, that way you are both hitting the rate limit.
the management SDK should have a backoff mechanism already in place. Also we have tools that will help you exporting and importing data from your spaces. [contentful-export](https://github.com/contentful/contentful-export) and [content-import](https://github.com/contentful/contentful-import)
can you provide me with a code snippet?

Best,
Khaled

**Comment by swatikurra** [comment]
Hi Khaled, 

Thanks for your response. Somehow, we managed it using timeout.
