### ISSUE TITLE
React-native issue : entry wont update

### ISSUE THREAD

**Issue by philohelp** [contentful/contentful-management.js#80]
I think I've tried all possible combinations but none of them seem to work. What do I do wrong ?

First : 
```
client.getSpace('<SPACEID>')
    .then((space) => {
         space.updateEntry({
         "sys": {
         id: "<ENTRYID>",
         version:45
          },
         "fields": {
         "job": {
           "fr-FR": "blablabla"
            }
         }
     })
})
```
=> Unhandled promise rejection TypeError: space.updateEntry is not a function

Second : 
```
client.getSpace('<SPACEID>')
		.then((space) => {
		  space.getEntry(<ENTRYID>)
			.then((entry) => {
				var ver = entry.sys.version
				var id = entry.sys.id
				entry = {
					"sys":{
						id: id,
						version:ver
					},
					"fields": {
						"job": {
							"fr-FR": "blablabla"
						}
					}
				}
				entry.update()
			})
		})
```
=> got entry.update() is not a function

Third : 
```
		.then((space) => {
		  space.getEntry(entryId)
			.then((entry) => {
				entry.fields.job = {"fr-FR": "blabla"}
				entry.update()
			})
		})
```
=> got Exception '-[__NSCFNumber length]: unrecognized selector sent to instance 0xb0000000000002d3'

Fourth : 

`entry.fields.job['fr-FR'] = 'blabla'`

=> same exception

```
ExceptionsManager.js:78 Exception '-[__NSCFNumber length]: unrecognized selector sent to instance 0xb000000000000013' was thrown while invoking sendRequest on target RCTNetworking with params (
        {
        data =         {
            string = "{\"fields\":{\"fireid\":{\"fr-FR\":\"bla\"},\"commission\":{\"fr-FR\":\"bla\"},\"dep\":{\"fr-FR\":\"bla\"},\"desc\":{\"fr-FR\":\"bla\"},\"email\":{\"fr-FR\":\"thp@ggg.com\"},\"firstname\":{\"fr-FR\":\"firstname\"},\"job\":{\"fr-FR\":\"blabla\"},\"name\":{\"fr-FR\":\"name\"},\"tel\":{\"fr-FR\":\"0675234573\"},\"type\":{\"fr-FR\":\"Collaborateur\"}}}";
            trackingName = unknown;
        };
        headers =         {
            accept = "application/json, text/plain, */*";
            authorization = "Bearer TOKEN";
            "content-type" = "application/vnd.contentful.management.v1+json";
            "x-contentful-user-agent" = "contentful-management.js/1.3.1";
            "x-contentful-version" = 1;
        };
        incrementalUpdates = 0;
        method = PUT;
        responseType = text;
        timeout = 0;
        url = "https://api.contentful.com:443/spaces/<SPACEID>/entries/<ENTRYID>";
    },
    139
)
```

**Comment by Khaledgarbaya** [comment]
hi @philohelp ,
to update an entry you can do the following : 
First, you need the entry object either, you create it or get and entry by id : 

```js
 // You can get an Entry object by
// 1. Creating one
var myEntry
space.createEntry({}).then((entry) => {myEntry = entry})

// 2. Get an existing one
space.getEntry('ENTRY_ID').then((entry) => {myEntry = entry})

// to Update an entry you can do the following
entry.fields.name['en-US'] = 'Blog Post'
entry.update()
.then(entry => console.log(entry.fields.name['en-US']))
```
again it depends on the fields of your entry, you might not need to do `[en-US]` if you don't have localized content

**Comment by philohelp** [comment]
Question opened in SO : http://stackoverflow.com/questions/42314820/contentful-content-management-node-lib-entry-wont-update
Problem probably related with axios / react-native. 
Got the API working with Fetch - lower level & old school solution but well, it works.

**Comment by Khaledgarbaya** [comment]
@philohelp ,
I think axios is using the http adapter when it is running in node which is not working well with ReactNative. I will add this in my list to investigate but I can't promise anything for now

**Comment by Khaledgarbaya** [comment]
@philohelp just to let you know we are updating our SDK soon with the latest axios version, So maybe you can give a try then. by next week we should have a beta version out.

**Comment by philohelp** [comment]
Great, I'll give it a look and let you know.

**Comment by axe312ger** [comment]
@philohelp could you fix your issue? :)

**Comment by philohelp** [comment]
I've released the app using fetch but I'll try and give a look tonight.

**Comment by Khaledgarbaya** [comment]
I am closing this issue for now please feel free to create a new one if you still have the issue
