### ISSUE TITLE
Fix the skipped integration tests

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful-management.js#82]
Right now we have few integration tests that we skip do to a random response type coming from the backend, we should bring them back once this issue resolved

**Comment by mariobodemann** [comment]
Rrtfrfty

**Comment by Khaledgarbaya** [comment]
![](https://cdn.meme.am/cache/instances/folder79/500x/30711079.jpg)

**Comment by mariobodemann** [comment]
I have no idea what has happen there! :gb:
