### ISSUE TITLE
Build 7.18.0 fails with typefest error

### ISSUE THREAD

**Issue by hgeist2** [contentful/contentful-management.js#848]
Using 7.18.0 with nestjs and typescript yields:

node_modules/contentful-management/dist/typings/entities/api-key.d.ts:166:25 - error TS2307: Cannot find module 'type-fest/source/simplify' or its corresponding type declarations.

166         payload: import("type-fest/source/simplify").Simplify<Pick<Pick<import("./app-definition").AppDefinitionProps, "name" | "src" | "locations" | "parameters">, "name" | "parameters"> & Partial<Pick<Pick<import("./app-definition").AppDefinitionProps, "name" | "src" | "locations" | "parameters">, "src" | "locations">>>;

**Comment by qauff** [comment]
updated to 7.17.7, I'm getting the same error.

**Comment by qauff** [comment]
rolled back until I found a working version: 7.17.6

**Comment by jugglingthebits** [comment]
Just tested with v7.20.1, this issue remains.

**Comment by Dara-To** [comment]
I still have this issue with the latest version 7.39.1.
