### ISSUE TITLE
Updating entry in contentful using PUT via postman and node-fetch

### ISSUE THREAD

**Issue by kushaltelus** [contentful/contentful-management.js#858]
As you can check below screenshot I tried to make PUT api call in the Contentful to update the entry.

When I try to hit GET call, everything works fine but don't understand here what is reason of this below error while making PUT call.

Did I missed anything here or anything wrong here?

NOTE: I changed all the variable while making call, spaceId, env, entryId and authorisation(passing access_token)

<img width="1109" alt="Screenshot 2021-05-10 at 7 40 30 PM" src="https://user-images.githubusercontent.com/67046488/117674023-f3652600-b1c8-11eb-8eb0-4172d5806e62.png">

**Code via node-fetch**

I fetch the entry then try to update here using below code.

` const fetch = require('node-fetch')

  fetch(`https://preview.contentful.com/spaces/{spaceId}/environments/{env}/entries/{entryId}`, {
              method: 'put',
              body: JSON.stringify({ fields: entry.fields }),
              headers: {
                Authorization: `Bearer ${contentfulClient.accessToken}`,
                'Content-Type': 'application/vnd.contentful.management.v1+json',
                'X-Contentful-Content-Type': entry.sys.contentType.sys.id,
                'X-Contentful-User-Agent': 'sdk contentful-management.js/7.18.2; platform node.js/v14.4.0; os macOS/19.5.0;',
                'X-Contentful-Version': entry.sys.revision
              }
            })
              .then(p => console.log(p))
              .catch(err => console.log(err))`

**Comment by DavidMWBP** [comment]
@kushaltelus After having discussed an issue I was having with the support team this ticket came up by chance, they noted that the baseUrl you are calling is wrong (https://preview.contentful.com/) versus (http://api.contentful.com/)
