### ISSUE TITLE
createUiExtensionWithId typing error

### ISSUE THREAD

**Issue by Xaz16** [contentful/contentful-management.js#868]
Hello!

I'm working with version `7.22.3` of contentful-management (latest for now) and trying to follow interface for this methods, but it looks like it is not correct one
If we check CMA we will see that we should wrap extension to object with key `extension`. https://www.contentful.com/developers/docs/references/content-management-api/#/reference/ui-extensions/extension/create-update-an-extension/console/js

But typing is not allow to do it in that way, if we follow typing we will have error like

```
ValidationFailed: {
  "status": 422,
  "statusText": "Unprocessable Entity",
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "required",
        "details": "The property \"extension\" is required here",
        "path": [
          "extension"
        ]
      },
      {
        "name": "unexpected",
        "details": "The property \"name\" is not expected",
        "path": [
          "name"
        ]
      },
      {
        "name": "unexpected",
        "details": "The property \"fieldTypes\" is not expected",
        "path": [
          "fieldTypes"
        ]
      },
      {
        "name": "unexpected",
        "details": "The property \"sidebar\" is not expected",
        "path": [
          "sidebar"
        ]
      },
      {
        "name": "unexpected",
        "details": "The property \"srcdoc\" is not expected",
        "path": [
          "srcdoc"
        ]
      }
    ]
  },
```

Repo with reproduction: https://github.com/Xaz16/contentful-management-issues/tree/master/createUiExtensionWithId

**Comment by loweisz** [comment]
Hey @Xaz16,

You are right, there was actually a mismatch between the types and the actual implementation. 
The types should be adjusted now and be correct after version `7.33.1`
