### ISSUE TITLE
getAllPreviewKeys typings

### ISSUE THREAD

**Issue by Xaz16** [contentful/contentful-management.js#869]
Hello!

I'm working with version `7.22.3` of contentful-management (latest for now) and trying to follow interface for this methods, but it looks like it is not correct one.

I'm trying to get accessToken field from item of collection from getAllPreviewKeys method (PreviewApiToken)
But I'm see PreviewApiToken interface and in runtime it is another interface most likely ApiKey with omitted field preview_api_key.

Repo for reproduce: https://github.com/Xaz16/contentful-management-issues/tree/master/getAllPreviewKeys

**Comment by Spring3** [comment]
`accessToken` is present in the typing since `v7.45.6`. Please see [this PR](https://github.com/contentful/contentful-management.js/pull/1037) for details
