### ISSUE TITLE
BadRequest during asset upload

### ISSUE THREAD

**Issue by nirajvenkat** [contentful/contentful-management.js#875]
I am uploading many image assets (~50 at a time) that are usually <10MB that are in .webp format.

When calling the Management API we getting the following errors for some assets:

- `BadRequest: The "Content-Length" header must be greater than 0`
- `Error: timeout of 30000ms exceeded`
The only way I have been able to solve this is by retrying the upload, but this does not work always. Nothing is outputted to error log.
The docs are not too clear about the HTTP `400 Bad Request`, could you please provide some more details?
is the timeout error expected since the API automatically waits? How do we tell if the retried request is successful?
 
We have thought about upgrading past Community tier but the rate limit for Content Management API (CMA) calls only goes up from 7 -> 10 on the later tiers so it seems unlikely that upgrading would solve our issues. Not sure how to implement rate-limiting on our side because setTimeout() seems to cause the timeout error.

My code for asset upload is similar to the provided in SDK examples:

            // This MGMT API call will request a space with the specified ID
            client.getSpace(process.env.CONTENTFUL_SPACE_ID).then(space => {
                // This API call will request an environment with the specified ID
                space.getEnvironment('master').then(environment => {
                    
                    // Now that we have an environment, we can get update assets in that space
                    Object.keys(assetUpdateHRLR).forEach(prodID => {
                        environment.getEntry(prodID)
                        .then(product => {

                            // Create/update asset
                            environment.createAssetFromFiles({
                                fields: {
                                    title: {...},
                                    file: {
                                        'en-US': {
                                        contentType: 'image/webp',
                                        fileName: ...
                                        file: fs.createReadStream(imgPath)
                                        }
                                    }
                                }
                            })
                            .then(asset => asset.processForAllLocales())
                            .then(asset => asset.publish())
                            .then .......

and the promise chaining continues for 2 other assets that are conditioned on the previous ones being published. After this the promise chain updates the entry where the newly created assets are linked.

**Comment by swanITworks** [comment]
I tried this approach but it seems to doesn't work. https://www.contentful.com/blog/2017/03/02/uploading-files-directly-to-contentful/

**Comment by swanITworks** [comment]
This approach works in my case: 

`client.getSpace(spaceId)
.then((space) => space.getEnvironment('master'))
.then((environment) => environment.createAssetFromFiles({
  fields: {
    title: {
      'en-US': 'Asset title'
    },
    description: {
      'en-US': 'Asset description'
    },
    file: {
      'en-US': {
        contentType: 'image/jpg',
        fileName: 'test.jpeg',
        file: fs.readFileSync(filePath),
      }
    }
  }
}))
.then((asset) => asset.processForAllLocales())
.then((asset) => asset.publish())
.catch(console.error)`

**Comment by swanITworks** [comment]
`client.getSpace(spaceId)
.then((space) => space.getEnvironment('master'))
.then((environment) => environment.createAssetFromFiles({
  fields: {
    title: {
      'en-US': 'Asset title'
    },
    description: {
      'en-US': 'Asset description'
    },
    file: {
      'en-US': {
        contentType: 'image/jpg',
        fileName: 'test.jpeg',
        file: fs.readFileSync(filePath),
      }
    }
  }
}))
.then((asset) => asset.processForAllLocales())
.then((asset) => asset.publish())
.catch(console.error)`

**Comment by nirajvenkat** [comment]
@swanITworks Thanks! Looks like that fixes one of the issues, namely, it no longer throws the `BadRequest`. However we still run into the timeout so my issue is only partially solved. I will go ahead and close the issue because my upload rate has substantially improved 👍 

Looks like contentful management API supports these types for the upload file: `file: string | ArrayBuffer | Stream`. 
`fs.readFileSync` reads a file at the path and returns `Buffer extends Uint8Array` which resolved to the expected `ArrayBuffer` type.
`fs.createReadStream` would return `fs.ReadStream` object which resolved to the expected `Stream` type. 
My guess is the API was not able to fill out the Content Length header based on `Stream`.
