### ISSUE TITLE
getEntryReferences is quite wrong

### ISSUE THREAD

**Issue by phawxby** [contentful/contentful-management.js#932]
Looking at this API when used on the Contentful side the argument should be `include`.
![image](https://user-images.githubusercontent.com/1090602/131919521-8662b6c2-89d3-46c0-ac04-7f554e41313b.png)

This isn't included in the options.
https://github.com/contentful/contentful-management.js/blob/7d2a0e20e36081978e4a376ff9dc42480c2d6c01/lib/create-environment-api.ts#L800-L812

In addition the return typings are wrong. CollectionProp is used.
https://github.com/contentful/contentful-management.js/blob/7d2a0e20e36081978e4a376ff9dc42480c2d6c01/lib/entities/entry.ts#L30-L31

This puts the results inside an item prop with Entry and Assets respectively. 
https://github.com/contentful/contentful-management.js/blob/7d2a0e20e36081978e4a376ff9dc42480c2d6c01/lib/common-types.ts#L156

This does not match the API response. Entry and Asset should both directly be an array.
![image](https://user-images.githubusercontent.com/1090602/131919719-a316f7b7-004e-43ca-9c8d-a38c634be3f6.png)

**Comment by Spring3** [comment]
This makes sense. Types are definitely incorrect as it is not a `Collection<>` of items, but an array instead.
Thanks for reporting

**Comment by Spring3** [comment]
Fixed as of `v4.45.4`
