### ISSUE TITLE
Create new entry failing

### ISSUE THREAD

**Issue by samjeffress** [contentful/contentful-management.js#97]
When creating an new entry as per guidelines https://contentful.github.io/contentful-management.js/contentful-management/3.3.4/typedef/index.html#static-typedef-Entry I get the following error: (getting the space works correctly - this error happens when invoking `space.createEntry({})`. 

```
{ BadRequest: {
  "status": 400,
  "statusText": "Bad Request",
  "message": "Missing object",
  "details": {},
  "request": {
    "url": "https://api.contentful.com:443/spaces/myspace/entries",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "contentful-management.js/3.3.4",
      "Authorization": "Bearer ACCESS_TOKEN",
      "user-agent": "node.js/v6.10.0",
      "Accept-Encoding": "gzip",
      "X-Contentful-Content-Type": {}
    },
    "method": "post"
  },
  "requestId": "removedforissue"
}
```

If I put content into body
```
space.createEntry({
      fields: {
        title: {'en-AU': slugThisMonth},
        body: {
          file: {'en-AU': pdfAssetId},
          effectiveDate: {'en-AU': new Date().toISOString()},
          name: {'en-AU': slugThisMonth}
        }
      },
    })
```
I get the following error (much the same, just with the extra body)
```
{ BadRequest: {
  "status": 400,
  "statusText": "Bad Request",
  "message": "Missing object",
  "details": {},
  "request": {
    "url": "https://api.contentful.com:443/spaces/myspace/entries",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "contentful-management.js/3.3.4",
      "Authorization": "Bearer ACCESS_TOKEN",
      "user-agent": "node.js/v6.10.0",
      "Accept-Encoding": "gzip",
      "X-Contentful-Content-Type": {
        "fields": {
          "title": {
            "en-AU": "cf-April-2017"
          },
          "body": {
            "file": {
              "en-AU": "afileid"
            },
            "effectiveDate": {
              "en-AU": "2017-04-05T04:09:55.461Z"
            },
            "name": {
              "en-AU": "cf-April-2017"
            }
          }
        }
      }
    },
    "method": "post"
  },
  "requestId": "removedforissue"
}
```

Following the documentation at https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries leads to the same path. 

I do have content types setup, in my space, and can't determine how to create an entry within a content type - maybe this is what i'm missing?

**Comment by axe312ger** [comment]
Hello @samjeffress,

on a first look, it looks like your request payload has the wrong structure.

The fields of a content type are always on the same level directly below `fields`.
You did it correct for the `title` field, but `file`, `effectiveDate` and `name` should not be within body, they should reside on the same level as the `title` field.

When this does not help, feel free to paste here a copy of your field structure from here:
`https://app.contentful.com/spaces/<your-space-id>/content_types/<your-content-type>/preview`
(The fields section would be enough)

Greetings from Berlin,
Benedikt

**Comment by samjeffress** [comment]
Thanks for your feedback @axe312ger!
The response back from the `/preview` was (excluding the system stuff):
```
{
  "name": "doc",
  "description": "",
  "displayField": "name",
  "fields": [
    {
      "name": "file",
      "id": "file",
      "type": "Link",
      "linkType": "Asset",
      "required": true,
      "validations": [
        {
          "assetFileSize": {
            "min": 1,
            "max": 26214400
          }
        }
      ],
      "localized": false,
      "disabled": false,
      "omitted": false
    },
    {
      "name": "effective date",
      "id": "effectiveDate",
      "type": "Date",
      "required": true,
      "validations": [],
      "localized": false,
      "disabled": false,
      "omitted": false
    },
    {
      "name": "name",
      "id": "name",
      "type": "Symbol",
      "required": true,
      "validations": [
        {
          "size": {
            "max": 50
          }
        }
      ]
    },
    {
      "name": "Jira Id",
      "id": "jiraId",
      "type": "Symbol"
    }
  ]
}
```

I've updated my code to have all the properties at the same level given your advice, but am still getting an error: 

```
 { BadRequest: {
  "status": 400,
  "statusText": "Bad Request",
  "message": "Missing object",
  "details": {},
  "request": {
    "url": "https://api.contentful.com:443/spaces/spaceid/entries",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "contentful-management.js/3.3.4",
      "Authorization": "Bearer ACCESS_TOKEN",
      "user-agent": "node.js/v6.10.0",
      "Accept-Encoding": "gzip",
      "X-Contentful-Content-Type": {
        "fields": {
          "file": {
            "en-AU": {
              "type": "Link",
              "linkType": "Asset",
              "id": "68xkZUWN56o4cOoeEyq0ee"
            }
          },
          "effectiveDate": {
            "en-AU": "2017-04-05T10:00:15.892Z"
          },
          "name": {
            "en-AU": "cf-April-2017"
          }
        }
      }
    },
    "method": "post"
  },
  "requestId": "c509b679120774f4c7a0765f5a3970d1"
}
```
no where in the request is there a mention of the content type (doc) - i'm just calling `space.createEntry(object)` - is there a way to set which content type the entry is?

Thanks for your help!
Sam

**Comment by axe312ger** [comment]
Ohh sorry, I overlooked that:

The first parameter of `space.createEntry()` is the content type as string, the second is your actual entry data.

Also, you need to create an asset first before you can attach it to the entry. (At least if you want to be present in the entry in the moment when the entry is created)

In total, it might later look like this:
```js
space.createAsset({
  fields: {
    file: {
      'en-AU': { 
        contentType: 'image/jpeg',
        fileName: 'test.jpg',
        upload: 'http://www.example.com/test.jpg'
      }
    }
  }
})
.then(asset => asset.processForAllLocales())
.then(asset => asset.publish())
.then(function(asset) {
  return space.createEntry('doc', {
    fields: {
      file: {
        'en-AU': {
          sys: {
            id: asset.sys.id,
            linkType: 'Asset',
            type: 'Link'
          }
        }
      },
      effectiveDate: {'en-AU': new Date().toISOString()},
      name: {'en-AU': slugThisMonth},
      jiraId: {'en-AU': jiraId}
    },
  })
})
.then(function(entry) {
  console.log(entry)
})
```


Cheers,
Benedikt

**Comment by samjeffress** [comment]
Fantastic, thanks for your help, it's working now.
I'm creating the asset in a separate step and passing the id through.
I should have looked at https://contentful.github.io/contentful-management.js/contentful-management/3.3.4/typedef/index.html#static-typedef-Space which has the details about create entity, rather than looking at the entity section.
Really appreciate your quick feedback

**Comment by axe312ger** [comment]
:) you are very welcome.

Well yeah, that reference docs need some love, we already have something prepared, expect proper documentation rolled out in the next weeks!

Closing this issue, have a nice day!

**Comment by bohdan-karapet-vaimo** [comment]
Hi, my comment is a bit outdated)
I faced with same error and found that we need to pass 2 arguments to `createEntry` - first one is content type id and second one is entry itself.

I use `"contentful-management": "^10.6.3"`

Example: `space.createEntry('contentTypeId', { fields: { ... } })`

In the example above you can see that entry JSON was added to "X-Contentful-Content-Type" header:
`"X-Contentful-Content-Type": {
        "fields": {
          "title": {
            "en-AU": "cf-April-2017"
          },
          ...
        }
      }`

But this header is responsible for content type, as per Contentful API examples (saw in Contentful trainig video).
